var cockpits = [
  {
    title: 'Honda CB900 Bol d’Or',
    shop: 'Andreu Nevado',
    img: './img/cockpit/cb900.jpg',
    link: 'http://www.returnofthecaferacers.com/2016/02/bol-dor-cb900-cafe-racer.html',
  },
  {
    title: 'CX500',
    shop: 'cx500forum CX66R',
    img: './img/cockpit/cx500_fourm.png',
    link: 'http://cx500forum.com/forum/cx-customization-mods-forum/26470-cm400t-fork-triple-cafe-racer-look-motogadget.html',
  },
  {
    title: '1976 BMW R60-6',
    shop: 'Worth Motorcycles',
    img: './img/cockpit/BMW-R60-6-Cafe-Racer-Cockpit.jpg',
    link: 'http://www.bike-urious.com/worth-motorcycles-build-1976-bmw-r606-cafe-racer/',
  },
  {
    title: '1963 Norton Atlas',
    shop: '',
    img: './img/cockpit/Norton-Atlas-Cafe-Racer-Cockpit2.jpg',
    link: 'http://www.bike-urious.com/1963-norton-atlas-cafe-racer/',
  },
  {
    title: '1986 R65 RACER',
    shop: 'Fuel Motorcycles',
    img: './img/cockpit/Fuel-R65Racer.jpg',
    link: 'http://thebikeshed.cc/2015/03/19/fuel-r65-racer/',
  },
  {
    title: '1975 CB550 \'Fade To Black\'',
    shop: 'Federal Moto',
    img: './img/cockpit/cb-cafe-racer-8.jpg',
    link: 'http://www.bikeexif.com/cb-cafe-racer',
  },
  {
    title: 'BMW R100 RS',
    shop: 'North East Customs',
    img: './img/cockpit/r100rs.jpg',
    link: 'http://www.bimmerfest.com/news/902313/custom-bmw-r100rs-cafe-racer-is-beautiful-in-blue/',
  },
  {
    title: 'Honda CB400F',
    shop: 'OtC Custom',
    img: './img/cockpit/Honda-CB400F-Cafe-Racer-1.jpg',
    link: 'http://www.bikebound.com/2016/08/18/honda-cb400f-cafe-racer/',
  },
  {
    title: '1974 BMW R90 Enduro \'Unexpected\'',
    shop: '',
    img: './img/cockpit/BMW-R90-Enduro-Cockpit.jpg',
    link: 'http://www.bike-urious.com/unexpected-1974-bmw-r90-enduro/',
  },
  {
    title: '1974 Moto Guzzi 850T',
    shop: '',
    img: './img/cockpit/Moto-Guzzi-850T-Cafe-Racer-Cockpit.jpg',
    link: 'http://www.bike-urious.com/1974-moto-guzzi-850t-cafe-racer/',
  },
  {
    title: '1966 Norton Atlas',
    shop: '',
    img: './img/cockpit/Norton-Atlas-Cafe-Racer.jpg',
    link: 'http://www.bike-urious.com/1966-norton-atlas-cafe-racer-3/',
  },
  {
    title: '1977 CB550F \'CRIMSON BRAT\'',
    shop: 'Smyth Innovations',
    img: './img/cockpit/CB550F_brat-gauge.jpg',
    link: 'http://www.smythinnovations.com/portfolio/cb550f-crimson-brat/',
  },
  {
    title: 'Triumph Scrambler',
    shop: 'Advrider davorallyfan',
    img: './img/cockpit/triump-scrm.JPG',
    link: 'http://advrider.com/index.php?threads/triumph-scrambler.141616/page-531',
  },
  {
    title: '1982 XV750 Virago',
    shop: 'Hageman Motorcycles',
    img: './img/cockpit/return-vx750.JPG',
    link: 'http://www.returnofthecaferacers.com/2016/09/virago-vx750-caferacer.html',
  },
  {
    title: 'Honda Grom Concept',
    shop: '',
    img: './img/cockpit/Concept-One-cockpit.jpg',
    link: 'https://bikebrewers.com/honda-grom-50-scrambler-concept/',
  },
  {
    title: '1978 Yamaha SR500',
    shop: 'Powder Monkees',
    img: './img/cockpit/1978-yamaha-sr500-2.jpg',
    link: 'http://www.bikeexif.com/1978-yamaha-sr500',
  },
  {
    title: '1975 Honda CB400F',
    shop: 'Salty Speed Co.',
    img: './img/cockpit/salty-cb400F_5.jpg',
    link: 'http://www.pipeburn.com/home/2014/06/11/1975-honda-cb400f-by-salty-speed-co.html',
  },
  {
    title: '1982 XS650',
    shop: 'Classified Moto',
    img: './img/cockpit/yamaha-xs650-2.jpg',
    link: 'ttp://www.bikeexif.com/yamaha-xs650-2',
  },
  {
    title: 'cb750',
    shop: 'Danny',
    img: './img/cockpit/9cb750.jpg',
    link: 'http://www.weareninetynine.co/dannys-cb750-cafe-racer/',
  },
  {
    title: '2003 CB750',
    shop: 'Rewheeled',
    img: './img/cockpit/honda-cb750-cafe-racer-02.jpg',
    link: 'http://greasengas.blogspot.com/2014/08/honda-cb750-cafe-racer.html#axzz4btbGlUEF',
  },
  {
    title: 'BMW R80',
    shop: 'WALZWERK',
    img: './img/cockpit/walzwerk-racing-bmw-cafe-racer-6-625x417.jpg',
    link: 'http://www.bikeexif.com/walzwerk-racing-bmw-r80-cafe-racer',
  },
  {
    title: 'CB750 Street Tracker',
    shop: 'Seaweed and Gravel',
    img: './img/cockpit/sw-tracker.jpg',
    link: 'https://seaweedandgravel.com/pages/custommotos',
  },
  {
    title: '\'I3',
    shop: 'Kott Motorcycles',
    img: './img/cockpit/i3.jpg',
    link: 'http://www.kottmotorcycles.com/builds/2014/1/8/black-nickel-cb500',
  },
  {
    title: 'Black Mamba',
    shop: 'Hookie co',
    img: './img/cockpit/black-mamba-top.jpg',
    link: 'http://hookie.co/portfolio/black-mamba-honda-cb550/',
  },
  {
    title: 'The Urban Brat',
    shop: 'Zeus Custom',
    donor: 'Stallions Max 250',
    img: './img/cockpit/zeus-brat.jpg',
    link: 'http://zeuscustom.shop/portfolio/tommy-highfilter-fashion-design-formen-project/',
  },
  {
    title: 'The Reticent',
    shop: 'Zeus Custom',
    donor: 'Stallions Max 250',
    img: './img/cockpit/zeus-reticent.jpg',
    link: 'http://zeuscustom.shop/portfolio/alexandra-stan-in-luxury-leather-stylefor-zara-fashion-brand/',
  },
  {
    title: 'Rebel Racer Limited Custom',
    shop: 'Zeus Custom',
    donor: 'Honda Rebel 300',
    img: './img/cockpit/zeus-rebel.jpg',
    link: 'http://zeuscustom.shop/portfolio/ibags-messenger-leather-bagsfor-men/',
  },
  {
    title: 'Pharell Racer',
    shop: 'Zeus Custom',
    donor: 'Yamaha SR 400',
    img: './img/cockpit/zeus-pharrel.jpg',
    link: 'http://zeuscustom.shop/portfolio/gentlemen-fashion-sets/',
  },
  {
    title: 'The Flat-Track',
    shop: 'Zeus Custom',
    donor: 'GPX Legend 200',
    img: './img/cockpit/zeus-flat-track.jpg',
    link: 'http://zeuscustom.shop/portfolio/the-flat-track/',
  },
  {
    title: 'Zodiac Star',
    shop: 'Zeus Custom',
    donor: 'GPX Legend 200',
    img: './img/cockpit/zeus-zodiac.jpg',
    link: 'http://zeuscustom.shop/portfolio/zodiac-star/',
  },
]

$(function () {
  setListItems(shuffle(cockpits));
})
