(function(k){var n=window.AmazonUIPageJS||window.P,p=n._namespace||n.attributeErrors,l=p?p("DigitalVideoLoggingAssets"):n;l.guardFatal?l.guardFatal(k)(l,window):l.execute(function(){k(l,window)})})(function(k,n,p){k.when("jQuery","dv-utils-stringify").register("logging",function(l,v){var p=function(c){var b=n.console;return b&&b[c]&&"function"===typeof b[c]?b[c]:function(){}},d={fatal:{consoleMethod:"error",logLevel:0,errorLevel:"FATAL"},error:{consoleMethod:"error",logLevel:1,errorLevel:"ERROR"},
warn:{consoleMethod:"warn",logLevel:2,errorLevel:"WARNING"},info:{consoleMethod:"info",logLevel:3,errorLevel:null},debug:{consoleMethod:"debug",logLevel:4,errorLevel:null},log:{consoleMethod:"log",logLevel:4,errorLevel:null},trace:{consoleMethod:"trace",logLevel:5,errorLevel:null}},h={},a;for(a in d)d.hasOwnProperty(a)&&(h[d[a].consoleMethod]=p(d[a].consoleMethod));var f=function(c){c=c||null;var b,r,e="";try{b=f.caller&&f.caller.caller&&f.caller.caller.caller||{},r=b.name||b._name||null}catch(a){}c&&
(e+=c.charAt(0).toUpperCase()+c.slice(1));r&&(e+=":"+r);return e},t=function(){var c=!1,b=/\baivDebug=1\b/;if(document.cookie.match(b)||document.location.search.match(b))c=!0;return c}(),w=function(){var c=!1,b=/\baivEmulateConsole=1\b/;if(document.cookie.match(b)||document.location.search.match(b))c=!0;return c}(),q;q=w?l("\x3cul /\x3e").addClass("dv-emulated-console").appendTo("body"):void 0;var x={},u=function(c,b){this._scriptName=c||null;this._log=b&&b.log?function(c,e,a){b.log(c,e,a)}:k.log?
function(c,b,a){k.log(c,b,a)}:function(c,b){n.ueLogError(null,{logLevel:b,message:c})}};for(a in d)d.hasOwnProperty(a)&&function(c){u.prototype[c]=function(){var b=d[c].consoleMethod,a=arguments,e=d[c].logLevel,g=d[c].errorLevel,m="string"===typeof this._scriptName?this._scriptName.toLowerCase():null,a=Array.prototype.slice.call(a),k="";((e=h&&h[b]&&"function"===typeof h[b]&&(t||m&&x[m])&&6>=e&&a)||g)&&(k=f(this._scriptName))&&a.unshift("["+k+"]");if(e&&(h[b].apply(n.console,a),w)){e=[];for(m=0;m<
a.length;m++)"object"===typeof a[m]?e.push(v(a[m])):e.push(a[m]);l("\x3cli /\x3e").text(e.join(" ")).addClass("dv-console-"+b).appendTo(q);q.scrollTop(q.get(0).scrollHeight)}g&&this._log&&this._log(v(a),g,k)}}(a);var g={create:function(a,b){g._mockConsole&&"object"===typeof g._mockConsole&&(h=g._mockConsole);g._mockDebugFlag&&"boolean"===typeof g._mockDebugFlag&&(t=g._mockDebugFlag);return new u(a,b)},extend:function(a,b,d){g._mockConsole&&"object"===typeof g._mockConsole&&(h=g._mockConsole);g._mockDebugFlag&&
"boolean"===typeof g._mockDebugFlag&&(t=g._mockDebugFlag);var e=a.prototype||a;b=new u(b,d);l.extend(e,b);for(var f in e)e.hasOwnProperty(f)&&"function"===typeof e[f]&&(e[f]._name=e[f].name||f);return a}};for(a in d)d.hasOwnProperty(a)&&(g[a]=function(){var c=a,b=arguments,d=g.create();d[c].apply(d,b)});return g});k.register("dv-utils-stringify",function(){return function(l){var k=[];return"object"===typeof JSON&&"function"===typeof JSON.stringify?JSON.stringify(l,function(l,d){if("object"===typeof d&&
null!==d){if(-1!==k.indexOf(d))return;k.push(d)}return d}):function d(h){var a;switch(h.constructor){case Object:a=[];for(var f in h)if(h.hasOwnProperty(f)&&-1===k.indexOf(h[f])){k.push(h[f]);var l=d(h[f]);l&&a.push('"'+f+'":'+l)}a="{"+a.join(",")+"}";break;case Array:a=[];for(f=0;f<h.length;++f)a.push(d(h[f]));a="["+a.join(",")+"]";break;case String:a='"'+h.toString()+'"';break;case Function:break;default:a=h.toString()}return a}(l)}})});
/* ******** */
(function(k){var u=window.AmazonUIPageJS||window.P,A=u._namespace||u.attributeErrors,f=A?A("DigitalVideoWebUtilityAssets"):u;f.guardFatal?f.guardFatal(k)(f,window):f.execute(function(){k(f,window)})})(function(k,u,A){k.when("jQuery","logging","dv-alert-templates-ready").register("aiv-alerts",function(f,b){function c(b,d,a,e){"undefined"===typeof d&&(d="inline");"undefined"===typeof e&&(e="info");d=["dv-alert-template",d,e].join("-");e=f("#"+d).html();g.debug("getAlert",d,e);"light"===a&&e&&(e=e.replace(/dv-alerts-dark/g,
"dv-alerts-light"));return l(f(e),b)}function l(b,d){if(0===b.length)g.error("_addContent missing $template",arguments);else{if(d)return b.find(".a-alert-content").html(d).end()[0].outerHTML;g.error("_addContent missing content",arguments)}}var g=b.create("aiv-alerts");return{getAlert:c,info:function(b,d,a){return c.call(c,b,d,a,"info")},warning:function(b,d,a){return c.call(c,b,d,a,"warning")},error:function(b,d,a){return c.call(c,b,d,a,"error")},success:function(b,d,a){return c.call(c,b,d,a,"success")}}});
k.when("A","jQuery","logging","dv-ajax-chunk","dv-ajax-widgets","dv-ux","aiv-client-side-metrics").register("dv-ajax-handler",function(f,b,c,l,g,h,d){var a=c.create("dv-ajax-handler"),e;e=function(b){this.options=b;this.nodes=[];a.debug("new AjaxHandler with",b);b=b.loggingName?b.loggingName:"dvweb-widget-reload-"+b.widgets.join("+");this.widgetMetrics=d.create({scope:b});a.debug("new AjaxHandler with",b,this.widgetMetrics)};e.prototype.callAjax=function(){var a=this,d=a.options.widgets.length,e=
b.Deferred();if(a.options.asin)return a.prepareWidgetsForRefresh(),a.widgetMetrics.ajaxStart(),f.ajax(a.options.url,{params:{asin:a.options.asin,widgets:a.options.widgets},chunk:function(b){b=l(b,a.options.widgets,a.options.DOMRootID);b.isValid?(f.trigger("dv:ajax:chunk:success:"+a.options.DOMRootID),b=g(b),b=b.reloadWidget({timeToFadeOut:0,timeToResize:0}),1>--d&&b.done(function(){a.chunksReplaced(e)})):1>--d&&a.chunksReplaced(e)},success:function(b,d,e){a.handleAjaxSuccess();a.widgetMetrics.ajaxSuccess({xhr:e})},
error:function(){a.removeUILock();a.options.reloadOnFailure&&(u.location.href="/gp/product/"+a.options.asin)},timeout:1E4}),e.promise()};e.prototype.chunksReplaced=function(a){a.resolve();this.widgetMetrics.ajaxDone()};e.prototype.handleAjaxSuccess=function(){this.removeUILock()};e.prototype.removeUILock=function(){for(var a=0,b=this.nodes.length,d;a<b;a++)d=this.nodes[a],h.enable(d)};e.prototype.updateUrl=function(){"function"===typeof u.history.replaceState?u.history.replaceState(this.options,this.options.title,
"/gp/product/"+this.options.asin):u.location.hash="#!"+this.options.asin};e.prototype.prepareWidgetsForRefresh=function(){var a,d=this.options.DOMRootID,e;for(a=0;a<this.options.widgets.length;a+=1)e=this.options.widgets[a],e=d?b("#"+d+" ."+e):b("#"+e),h.disable(e),this.nodes.push(e)};return function(a){return new e(a)}});k.when("jQuery","A").register("dv-ajax-chunk",function(f,b){var c;c=function(b,g,h){this.isValid=!1;this.expectedWidgets=g;f.isArray(b)&&3===b.length&&(this.id=b[1],this.data=b[2],
this.DOMRootID=h,this.validateChunk())};c.prototype.validateChunk=function(){-1!==f.inArray(this.getChunkRawID(),this.expectedWidgets)&&this.getChunkData()&&(this.isValid=!0)};c.prototype.getChunkData=function(){return f.trim(this.data)};c.prototype.getChunkRawID=function(){return this.id};c.prototype.getDOMSelector=function(){var b=this.getChunkRawID();return this.DOMRootID?f("#"+this.DOMRootID+" ."+b):f("#"+b)};return function(b,g,h){return new c(b,g,h)}});k.when("A","logging","dv-ux").register("dv-ajax-widgets",
function(f,b,c){var l=b.create("dv-ajax-widgets"),g,h;g=function(b){this.nodeID=b.getChunkRawID();this.widgetHTML=b.getChunkData();this.$node=b.getDOMSelector()};g.prototype.reloadWidget=function(b){var a=this;if(a.$node.length)return h=c.replaceContent(a.$node,a.widgetHTML,b),h.done(function(){l.debug("dv:ajax:chunk:replaced:"+a.nodeID);f.trigger("dv:ajax:chunk:replaced:"+a.nodeID)}),h};return function(b){return new g(b)}});k.when("A","dv-ajax-handler","ready").register("dv-ajax-reload",function(f,
b){var c=f.$,l={widgets:"dv-dp-title-content dv-dp-left-content dv-action-box dv-main-bottom-section dv-episode-list dv-center-aiv dv-customer-reviews".split(" "),reloadOnFailure:!1,title:document.title,url:"/gp/video/apps/ajax-detail-page"};return{getWidgets:function(g){g=c.extend({},l,g);return b(g).callAjax()}}});k.when("A","jQuery","logging","aiv-util-event","a-modal","dv-modal-stack","dv-modal-templates-ready").register("aiv-modal",function(f,b,c,l,g,h){function d(d){var c=a(d);d=b("\x3cdiv/\x3e").attr({id:c.id});
var E=g,v={},w={},v={},k=[],C=[],q;G&&f.capabilities.mobile&&c.hasScrollableContent&&(E=G,J=!0);var v=c.id,u=e(c),z=t(c),A=n(c),D=J?!1:!!c.hideHeader,N=x(c),I=c.cache||!1,K;K="dark"===c.theme?"none":c.padding;var M=c.maxWidth||c.width||400,L;L="dark"===c.theme?!0:!1;v={name:v,url:u,content:z,header:A,hideHeader:D,footer:N,cache:I,width:"90%",padding:K,"max-width":M,closeButton:L?!1:y(c)};q=E.create(d,v);p.debug("created modal with args:",v,q);l.bestowEvents(w);r(c.id,w);H(c,w,k,C);q._display=q.show;
v={on:B(w),getName:function(){return c.id},_show:function(){q._display()},show:function(){h.add(q);return q},showImmediate:function(){h.replaceTop(q)},remove:function(){p.debug("remove: "+c.id,q,c);F(k,C);E.remove(c.id)}};b.extend(q,v);if("dark"===c.theme||"none"===c.padding)q.on("afterShow",function(a){a=q.$popover;var b=a.find(".a-popover-inner, .a-secondary-view-inner");a.find(".a-popover-wrapper").addClass("dv-aui-dark-wrapper");b.addClass("dv-modal-wrapper-dark");p.debug("afterShow",c);b.css({padding:0})}),
q.on("ajaxContentLoaded",function(a){q.$popover.append(m(c.theme))});q.on("afterHide",function(a){E.remove(c.id)});q.on("closeModal",function(a){E.remove(c.id)});q.on("optOut",function(a){a.url&&f.get(a.url+a.checked)});return q}function a(a){var d;d=b(a.selector||"#"+a.id).data("dv-modal");var e={};A||(z.submitTemplate=b(D.submitTemplate).html(),z.cancelTemplate=b(D.cancelTemplate).html(),z.linkTemplate=b(D.linkTemplate).html(),z.checkboxTemplate=b(D.checkBoxTemplate).html(),p.debug("_init:",z),
A=!0);b.extend(!0,e,d,a);e.originalId=e.id||e.name;e.id=(e.id||e.name)+"_"+I++;p.debug("getOptions:",{args:a,dataAttributes:d,options:e});return e}function e(a){var d="",e=a.url;if(e)return a.urlParameters&&(d=e.match(/\?/)?"\x26":"?",d+=b.param(a.urlParameters)),e+d}function t(a){var d,e;(e=a.content)||(e=["#a-popover-",a.name].join(""),d=b(e),p.info("element: "+e,d),e=d.length?d.html():"");if(!e){e="";d=a.url;var c=b(a.selector||"#"+a.originalId);p.info({url:d,element:c});d||(e=c.html(),p.debug("_createModal: no url or content, element html",
e))}p.info("_getContent",e);d=e;e=a.theme;if(!d)return"";e&&(c="dv-modal-wrapper-"+e,d=b("\x3cdiv /\x3e").addClass(c).append(d),y(a)&&d.append(m(e)),d=d[0]);return d}function m(a){a="dv-modal-close-button-"+a;return b('\x3cbutton type\x3d"button" role\x3d"button" data-action\x3d"a-popover-close" class\x3d"a-declarative"\x3e\x3cspan\x3eX\x3c/span\x3e\x3c/button\x3e').addClass(a)}function n(a){var b=a&&a.header||{};a=a&&a.hideHeader;p.info("hideHeader:",a,b);return a?"":b.text||""}function x(a,d){var e=
"",c=a.buttons,h={},g=a.id;p.debug("_getFooter args:",a);c&&b.each(c,function(a,b){var d=v({id:g,elemOptions:b,template:z[b.type+"Template"]});p.debug("_getFooter buttonObj:",d);e+=d.html});a.optOut&&a.optOut.url&&(h=v({id:g,elemOptions:{type:"checkbox",text:a.optOut.text},template:z.checkboxTemplate}),e+=h.html);return e}function B(a){return function(b,d,e){p.debug("on:",a,b,d,e);a.on([b],d,e)}}function y(a){var b=!1;"undefined"!==typeof a.closeButton?b=a.closeButton:"undefined"!==typeof a.showCloseButton&&
(b=a.showCloseButton);return!!b}function r(a,d){b.each(u,function(b,e){f.on("a:popover:"+e+":"+a,function(a){d.fire(e,a)})})}function H(a,d,e,c){p.debug("_addEventListeners",a,d,e,c);a.optOut&&a.optOut.url&&(C("#"+a.id+"-checkbox","optOut",{url:a.optOut.url},d),c.push({id:a.id}));a.buttons&&b.each(a.buttons,function(b,c){var h=c.id||a.id+"-"+c.type,h={name:h,id:"#"+h,eventArgs:c.eventArgs,customEvent:c.customEvent||"dv:dv-modal:"+c.type,customActionEndpoint:c.customActionEndpoint};q(h,d,a.isDeclarative);
e.push(h)})}function v(a){var b=a.elemOptions||{},d=a.template||"",e={};p.debug("_getFooterUIElement args:",a);e.html="";e.name=b.id||a.id+"-"+b.type;e.id="#"+e.name;e.text=b.text;e.url=b.url;e.text&&d&&(e.html=w(d,e.name,e.text,e.url));p.debug("_getFooterUIElement element:",e);return e}function w(){var a=Array.prototype.shift.call(arguments),b=arguments,a=a.replace(/(\r\n|\n|\r)|(^\s+|\s+$)/gm,"");p.debug("_formatTemplate:",a,b);if(a)return a.replace(/\{(\d+)\}/g,function(a,e){return"undefined"!==
typeof b[e]?b[e]:a});p.error("Template missing",b)}function C(a,e,d,c){p.debug("_addCheckBoxEventListener:",a,e,d);b("body").delegate(a+" input[type\x3d'checkbox']","change",function(){d.checked=!!this.checked;p.debug(a+" checkbox changed",d);c.fire(e,d)})}function q(a,e,d){p.debug("_addButtonEventListener button:",e,a);b("body").delegate(a.id,"click",function(){d?f.trigger(a.customEvent,a.eventArgs):e.fire(a.customEvent,a.eventArgs)})}function F(a,e){p.debug("_removeEventListeners",a,e);b.each(a,
function(a,e){b("body").undelegate(e.id,"click")});b.each(e,function(a,e){b("body").undelegate(e.id+" input[type\x3d'checkbox']","change")})}var p=c.create("aiv-modal"),u=["afterHide","afterShow","close","ajaxContentLoaded"],D={submitTemplate:"#SubmitTemplate",cancelTemplate:"#CancelTemplate",linkTemplate:"#LinkTemplate",checkBoxTemplate:"#CheckBoxTemplate"},z={},A=!1,I=0,J=!1,G;k.when("a-secondary-view").execute(function(a){G=a});f.declarative("aiv-modal","click",function(b){b=b.data;var e=a(b),
c;b.isDeclarative=!0;p.debug("declarative data:",b);c=d(b);e.showImmediately?c.showImmediate():c.show();f.on("aiv:modal:close:declarative",function(){c.remove();f.off("aiv:modal:close:declarative")})});b("body").delegate('[data-action\x3d"aiv-modal"] a',"click",function(a){a.preventDefault()});return{create:d}});k.when("A","jQuery","logging").register("dv-modal-stack",function(f,b,c){function l(b){if(!a(b)){var c=b.attrs("name");e.debug("[add]",c,g());b.on("afterHide",d);m[c]=!0;t.unshift(b);g()||
h(b,0)}}function g(a){if("undefined"===typeof a)return k;e.debug("[_isActive] set",a);k=a}function h(a,b){e.debug("[_displayModal]",a);g(!0);a._show()}function d(a){f.delay(function(){var a,b;b=t.pop();e.debug("[_finishedHiding]",t.length,b);b&&(b=b.attrs("name"),m[b]=!1);g(!1);if(b=t.length)a=t[b-1],h(a,600);e.debug("[_finishedHiding] nextModalInQueue",a)},"undefined"!==typeof a.delay?a.delay:600)}function a(a){for(var b=t.length,d=0;d<b;d++)if(t[d]===a)return e.debug("[_contains] stack already contains",
a,t),!0;return!1}var e=c.create("dv-modal-stack"),t=[],m={},k=!1;return{add:l,replaceTop:function(b){if(!a(b))if(0===t.length)l(b);else{var c=b.attrs("name");e.debug("[addAsNext]",c,g());m[c]=!0;b.on("afterHide",d);c=t.pop();t.push(b);t.push(c);c.remove();h(b,0)}},_internal:{_isActive:g,_types:m,_stack:t,_displayModal:h,_afterHide:d}}});k.when("dv-get-reftag-from-url","dv-send-analytics","dv-url-param","dv-get-elem-by-alias").register("dv-utilities",function(f,b,c,l){return{getRefTagFromURL:f,sendAnalytics:b,
urlParam:c,getElemByAlias:l}});k.register("dv-get-reftag-from-url",function(){return function(f){if(f&&(f=f.match(/\bref_?=([^?&]*)\b/i))&&2<=f.length)return f[1]}});k.when("jQuery").register("dv-send-analytics",function(f){return function(b){b&&f.ajax({url:"/gp/video/widgets/main-section/ajax/analytics.html/ref\x3d"+b,data:{},dataType:"json",timeout:1E4})}});k.register("dv-url-param",function(){var f;return function(b){if(!f){f={};for(var c=(document.location.search||"").substring(1).split("\x26"),
l=0;l<c.length;l++){var g=c[l].split("\x3d");f[g[0]]=g[1]}}return b?f[b]:f}});k.when("A","jQuery").register("dv-get-elem-by-alias",function(f,b){return function(c,f){if(c||f)return b(c).filter(function(c,h){var d=b(h).data("aliases");return!(!d||-1===b.inArray(f,d.split(",")))})}});k.when("A","jQuery","logging").register("dv-content",function(f,b,c){function l(d,a){g.info({element:d,argsObj:a});var e=b.extend(!0,{},h,a),c="."+e.className,e=b("\x3c"+e.wrapperTag+" /\x3e").addClass(e.className),f=d.children(c);
f.length||(d.wrapInner(e),f=d.children(c).css({overflow:"hidden"}));return f}var g=c.create("dv-content"),h={wrapperTag:"div"};return{replaceContent:function(d,a,e){function c(){y.removeAttr("style");k.resolve();"function"===typeof r.callback&&r.callback()}function h(){f.animate(y,{opacity:1,top:0},r.timeToFadeIn,r.easing,c)}g.info({element:d,content:a,args:e});var k=b.Deferred(),x=b(a),B=d.height(),y=l(d,{className:"js-dv-replace-content-wrapper"}),r={};b.extend(!0,r,{timeToFadeIn:300,timeToFadeOut:200,
timeToResize:200,easing:"ease-in-out",fadeInMovePercent:.15,callback:null},e);!d instanceof b&&g.error("replaceContent $element is not a jQuery object",d);f.animate(y,{opacity:0},r.timeToFadeOut,r.easing,function(){var a={height:y.empty().append(x).height(),top:0*r.fadeInMovePercent};y.height(B).css({position:"relative"});f.animate(y,a,r.timeToResize,r.easing,h)});return k.promise()},wrapContent:l,hideContent:function(b,a,e){b.length&&(b=l(b,{className:"js-dv-hide-content-wrapper"}),f.animate(b,{opacity:0}))},
showContent:function(b,a,e){if(b.length){var c=b.find(".js-dv-hide-content-wrapper");c.length&&f.animate(c,{opacity:1},function(){c.removeAttr("style")})}}}});k.when("A","jQuery","logging").register("dv-extendable-element",function(f,b,c){var l=c.create("dv-extendable-element"),g=function(b){l.info(b);this.$element=b};g.prototype.element=function(){l.info(this.$element);return this.$element};g.prototype.addBehaviours=function(){var c=this,d=Array.prototype.slice.call(arguments);l.debug(d);b.each(d,
function(a,b){for(var d in b)b.hasOwnProperty(d)&&(c[d]=c.extensify(b[d],d))})};g.prototype.extensify=function(b){var d=this;l.info(b);return function(){var a=Array.prototype.slice.call(arguments);a.unshift(d.$element);d._value=b.apply(this,a);return d}};g.prototype.value=function(){l.info(this);return this._value};return function(b){l.info(b);var d=Array.prototype.slice.call(arguments,1),a=new g(b);d&&a.addBehaviours.apply(a,d);return a}});k.when("A","jQuery","logging","dv-content").register("dv-interactive",
function(f,b,c,l){var g=c.create("dv-interactive"),h={disableOpacity:.2},d=b("\x3cdiv /\x3e").addClass("dv-disable-overlay js-dv-disable-overlay");return{disable:function(a,e){g.debug(a);var c=b.extend(!0,{},h,e),f,k;a&&a.length&&!a.find(".js-dv-disable-overlay").length&&(k=d.clone(),k.click(function(a){a.preventDefault()}),f=l.wrapContent(a,{className:"js-dv-disable-wrapper"}),f.animate({opacity:c.disableOpacity},function(){f.css({visibility:"hidden"})}),a.addClass("dv-disable-wrapper").append(k))},
enable:function(a){var b;g.debug(a);a&&a.length&&(a.find(".js-dv-disable-overlay").remove(),b=a.find(".js-dv-disable-wrapper"),b.css({visibility:"visible",opacity:0}),b.animate({opacity:1},function(){b.removeAttr("style")}))}}});k.when("A","jQuery","logging").register("dv-spinner",function(f,b,c){function l(b){return!!b.find("."+a.spinnerWrapper).length}function g(){return'\x3cdiv class\x3d"dv-spinner"\x3e\x3c/div\x3e'}var h=c.create("dv-spinner"),d={theme:"light",size:"medium"},a={spinnerContainer:"dv-spinner-container",
spinnerWrapper:"dv-spinner-wrapper"};return{addSpinner:function(e,c){h.debug(e,c);if(!l(e)){var f=b.extend(!0,{},d,c);h.debug(f.theme,f.size);var f=b(g()),k=a.spinnerWrapper;h.debug(f,k);f=b("\x3cdiv /\x3e").addClass(k).append(f).clone();e.addClass(a.spinnerContainer).append(f)}},removeSpinner:function(b){b.length&&(b.find("."+a.spinnerWrapper).remove(),b.removeClass(a.spinnerContainer))},hasSpinner:l,getSpinner:g,getSpinnerWrapper:function(b){return b.find("."+a.spinnerWrapper)}}});k.when("A","jQuery",
"logging","dv-content").register("dv-text",function(f,b,c,l){var g=c.create("dv-replace-text");return{replaceText:function(c,d,a){function e(){g.info("cleanUp",c);v.remove();m.removeAttr("style").removeClass("js-dv-replace-text-new").addClass("js-dv-replace-text-wrapper");c.height("auto").removeClass("js-dv-replace-text-progress");w.callback()}g.info(c,d,a);var k=b.Deferred(),m=b(d),n=c.outerWidth(),x=c.outerHeight(),B=c.css("padding-top"),y=c.css("padding-bottom"),r=c.css("padding-left"),H=c.css("padding-right"),
v=l.wrapContent(c,{className:"js-dv-replace-text-wrapper",wrapperTag:"span"}),w={},C={},q={},F={},p={};b.extend(!0,w,{reverse:!1,easing:"ease-out",timeToChange:150,callback:function(){k.resolve()}},a);!c instanceof b&&g.error("replaceContent $element is not a jQuery object",c);m.length||g.error("replaceContent $content is not an element",d);c.hasClass("js-dv-replace-text-progress")?v.html(d):(C={position:"absolute",width:n,height:x,left:0,opacity:1,top:0},q={top:w.reverse?x:-x},F={position:"absolute",
width:n,height:x,paddingBottom:y,paddingTop:B,paddingLeft:r,paddingRight:H,top:w.reverse?-x:x,left:0,opacity:0},p={top:0,opacity:1},c.css({position:"relative",height:x}).addClass("js-dv-replace-text-progress"),v.css(C),m.addClass("js-dv-replace-text-new").css(F),c.append(m),f.animate(v,{opacity:0},w.timeToChange/2,w.easing),f.animate(v,q,w.timeToChange,w.easing),f.animate(m,p,w.timeToChange,w.easing,e));return k.promise()}}});k.when("jQuery","logging","dv-extendable-element","dv-content","dv-text",
"dv-interactive","dv-spinner").register("dv-ux",function(f,b,c,l,g,h,d){b.create("dv-ux");return{disable:h.disable,enable:h.enable,addSpinner:d.addSpinner,removeSpinner:d.removeSpinner,getSpinner:d.getSpinner,replaceText:g.replaceText,replaceContent:l.replaceContent,wrapContent:l.wrapContent,hideContent:l.hideContent,showContent:l.showContent}});k.when("jQuery","logging","dv-extendable-element","dv-content","dv-text","dv-interactive","dv-spinner").register("dv-ux-mixins",function(f,b,c,l,g,h,d){b.create("dv-ux");
return{extendable:c,content:l,text:g,interactive:h,spinner:d}});k.when("A","jQuery","logging","dv-ux").register("dv-buttons",function(f,b,c,l){function g(a,d,c){d=b("\x3cspan /\x3e").append(d);l.replaceText(a.find("."+n.buttonText),d,{reverse:c})}function h(a,b,d,c){b&&(a.removeClass([n.confirm,n.processing,n.primary].join(" ")),(b=n[b]||"")&&a.addClass(b));d&&g(a,d,c)}function d(){k.log("[resetConfirmButtons]");var c=b("."+n.confirm);c.length&&c.each(a);m&&b(document).unbind("click",d)}function a(a,
d){var c=b(d),e=c.data("orinalText");h(c,"primary",e,!0)}function e(a){if(!a.data("orinalText")){var b=a.text();a.data("orinalText",b)}}var k=c.create("dv-button"),m=f.capabilities.touch,n={confirm:"dv-confirm",processing:"js-dv-processing dv-button-processing",primary:"dv-oneclick",buttonText:"dv-button-text"};return{buttonContent:g,buttonState:h,addProcessingState:function(a,d){k.log("[addButtonProcessingState]");a.each(function(a,c){e(b(c));h(b(c),"processing",d)})},resetButtonsOriginalState:function(b){b.length&&
b.each(a)},addConfirmState:function(a,c){k.log("[addButtonConfirmState]");a.each(function(a,d){e(b(d));h(b(d),"confirm",c)});m&&b(document).bind("click",d)},resetConfirmButtons:d}});k.when("A").register("dv-analytics",function(f){var b=f.$;return{log:function(c,f,g){var h="",d="",a="",e="";g=null!==g?g:{};"undefined"!==typeof g.pageType&&(h=g.pageType);"undefined"!==typeof g.subPageType&&(d=g.subPageType);"undefined"!==typeof g.store&&(a=g.store);"undefined"!==typeof g.requestId&&(e=g.requestId);
b.ajax({url:"/gp/video/analytics/clickstream-logger.html",data:{asin:null!==c?c:"",pageType:h,subPageType:d,pageAction:null!==f?f:"",tabId:a,pageRequestId:e},dataType:"json",type:"POST",timeout:1E4})},recordWeblab:function(c,f,g){b.ajax({url:"/gp/video/analytics/weblab-logger.html",data:{weblab:c,treatment:f,rid:g.requestId},dataType:"json",type:"POST",timeout:1E4})},constants:{PLAY_TRAILER:"PlayTrailer",PLAY_STREAM:"PlayStream"}}});k.when("A","jQuery","logging","aiv-modal").register("dv-async",function(f,
b,c,l){return{create:function(g,h){function d(a){var b="";a&&"function"===typeof a&&(b=a.name,b||(b=(a=/^function\s+([\w\$]+)\s*\(/.exec(a.toString()))?a[1]:""));return b}function a(a,b){l.create({id:b}).show();r.error(a)}function e(){return{customError:function(){},timeout:function(b,d,c){a(c,"dv-modal-ajax_timeout")},error:function(b,d,c){a(c,"dv-modal-ajax_error")},abort:function(a,b,d){r.warn("abort")},parsererror:function(b,d,c){a(c,"dv-modal-ajax_error")}}}function t(a){var b=c.create([y,d(a)].join(":"),
h||k);return function(){try{a.apply(this,arguments)}catch(d){b.error(d)}}}function m(a){var d=[200,302],c=b.extend({},e(),a);return{success:function(a){r.error("done method must be overridden")},error:function(a,e,f){0>b.inArray(parseInt(a.status,10),d)&&r.warn(a.status);if(e&&"function"===typeof c[e])c[e](a,e,f);else c.error(a,e,f);c.customError(a,e,f)}}}function n(a,d,c){var e=0,f=c&&c.maxRetrys||0;c=m(c);var g={},h,l;b.extend(g,{accepts:void 0,contentType:void 0,cache:!1,indicator:"",method:"post",
params:{},timeout:1E4,withCredentials:!0},c,d);r.debug(g);g.success=t(g.success);h=t(g.error);g.error=h;l=function(){r.log(e);f>++e?g.error=l:g.error=h;x(a,g)};f>e&&(g.error=l);x(a,g)}function x(a,c){a.match("^(/|"+(u.location.protocol+"//"+u.location.host)+")")?f.ajax(a,c):b.ajax(a,B(c))}function B(a){r.debug("convertOptions",a);var c={data:a.params,success:a.success,error:a.error};b.support.cors?(c.dataType="json",c.type="POST",c.crossDomain=!0,c.xhrFields={withCredentials:!0}):(c.dataType="jsonp",
c.type="GET",c.jsonpCallback=a.jsonpCallback);return c}var y=g||"dv-async",r=c.create(y,h||k);return{wrap:t,delay:function(a,b){f.delay(t(a),b)},ajax:n,get:function(a,b,c,d){c=c||{};c.method="get";c.success=b;return n(a,c,d)},post:function(a,b,c,d,e){d=d||{};d.method="post";d.params=b;d.success=c;return n(a,d,e)},deferred:function(){function a(b,c){return function(a){b(t(a));return c}}var c=b.Deferred(),d=c.promise();b.each(["done","fail","always","then"],function(b,c){"then"===c?d.then=function(a,
b){d.done(a).fail(b);return d}:d[c]=a(d[c],d)});c.promise=function(){return d};return c}}}}});k.when("logging").register("aiv-client-side-metrics",function(f){var b=f.create("aiv-client-side-metrics"),c=u.uet,l=u.ues,g=u.uex,h=u.ue,d=function(a){b.log("[CSM] new with options",a);this.scope=a&&a.scope};d.prototype.record=function(a,d){b.log("[CSM] uet "+this.scope+" "+a,d);"function"===typeof c&&c(a,this.scope,d)};d.prototype.set=function(a,c){b.log("[CSM] ues "+this.scope+" "+a,c);"function"===typeof l&&
l(a,this.scope,c)};d.prototype.publish=function(a,c){b.log("[CSM] uex "+this.scope+" "+a,c);"function"===typeof g&&g(a,this.scope,c)};d.prototype.counter=function(a,c,d){b.log("[CSM] ue.count "+a+" "+c);c=c||1;d=d||{scope:this.scope};h&&"function"===typeof h.count&&h.count(a,(h.count(a,void 0,d)||0)+c,d)};d.prototype.timeOfClick=function(a){this.record("tc",a)};d.prototype.experiment=function(a){this.record("x",a)};d.prototype.calculationEnd=function(a){this.record("pc",a)};d.prototype.clickToNavStart=
function(a){this.record("ns",a)};d.prototype.clickToNavEnd=function(a){this.record("ne",a)};d.prototype.clickToBodyBegin=function(a){this.record("bb",a)};d.prototype.clickToATF=function(a){this.record("af",a)};d.prototype.clickToCF=function(a){this.record("cf",a)};d.prototype.clickToBodyEnd=function(a){this.record("be",a)};d.prototype.requestId=function(a){this.set("id",a)};d.prototype.startTime=function(){this.set("t0",new Date)};d.prototype.baseOnClientTime=function(){this.set("ctb","1")};d.prototype.clickToPageLoaded=
function(a){this.publish("ld",a)};d.prototype.ajaxStart=function(a){this.timeOfClick(a)};d.prototype.ajaxSuccess=function(a){var b=a.requestId;a=a.xhr;!b&&a&&"function"===typeof a.getResponseHeader&&(b=a.getResponseHeader("x-amz-id-1"));this.requestId(b);this.startTime();this.baseOnClientTime()};d.prototype.ajaxDone=function(a){this.clickToBodyEnd(a);this.clickToPageLoaded(a)};return{create:function(a){return new d(a)}}});k.when("A","jQuery").register("dv-reftag",function(f,b){function c(c){b.ajax({url:"/gp/video/widgets/main-section/ajax/analytics.html/ref\x3d"+
c,data:{},dataType:"json",timeout:1E4})}f.declarative("dv-record-reftag","click",function(b){b.data&&b.data.reftag&&c(b.data.reftag)});return{record:c}});k.when("jQuery").register("dv-eventBinder",function(f){return{bind:function(b){b=b||document;this._eventRegistry=this._eventRegistry||[];var c=this,l=/^\s*(.+)\s+(\S+)\s*$/,g=function(a,d,g){var h=function(a,b){a.source=f(this);g.call(c,a,b)};if(a)if(f(b).on)f(b).on(d,a,h);else f(b).delegate&&f(b).delegate(a,d,h);else f(b).bind(d,h);c._eventRegistry.push({baseElement:b,
selector:a,eventName:d})},h;for(h in this){var d=h.match(l);d&&this[h]&&"function"===typeof this[h]&&g("subscribe"!==d[1]?d[1]:void 0,d[2],this[h])}},unbind:function(){for(var b=this._eventRegistry.length-1;0<=b;b--){var c=this._eventRegistry[b];c.selector?f(c.baseElement).off?f(c.baseElement).off(c.eventName,c.selector):f(c.baseElement).undelegate&&f(c.baseElement).undelegate(c.selector,c.eventName):f(c.baseElement).unbind(c.eventName);this._eventRegistry.splice(b,1)}}}});k.when("A","jQuery","logging").register("dv-form",
function(f,b,c){var l=c.create("dv-form");return{data:function(c,f){l.debug(c,f);var d=c.find("input").serializeArray(),a={};b.each(d,function(b,c){c.name&&(a[c.name]=c.value)});return a}}});k.when("jQuery","logging","dv-async").register("promise-pipeline",function(f,b,c){return{create:function(l,g,h){function d(a){m.errors=m.errors||[];e.error(a);m.errors.push(a)}function a(b){var c,g,h;if(b>=k.length)n.resolve(m);else if(c=k[b]||{},h=[c.name,"step:",b].join(" "),c.getPromise&&"function"===typeof c.getPromise){e.debug(h+
" got promise",{step:b,currentStep:c,options:m});try{g=c.getPromise(m),g.done(function(c){f.extend(!0,m,c);e.debug(h+" done",m,c);a(++b)}),g.fail(function(a){f.extend(!0,m,a);e.debug(h+" fail",m,a);n.reject(m)})}catch(l){d(l),n.reject(m)}}else d(h+" getPromise is not a function"),a(++b)}g=g||"promise-pipeline";var e=b.create(g,h);h=c.create(g,h);var k=l.promises,m=l.options,n=h.deferred();a(0);return n.promise()},step:function(b,f,h){var d=c.create(b,h);return{name:b,getPromise:function(a){var b=
d.deferred();f(b,a);return b.promise()}}}}});k.when("logging").register("dv-register-once",function(f){var b=f.create("dv-content");return function(c,f){k.now(c).execute(function(g){if("undefined"!==typeof g)b.info("Tried to re-register "+c,f);else try{k.declare(c,f)}catch(h){b.info("Tried to re-register "+c,f)}})}});k.when("A","jQuery","logging").register("aiv-util-event",function(f,b,c){var l=c.create("aiv-util-event");return{bestowEvents:function(c){var f={};c.fire=function(c,a){var e,g,k,n;e=
"string"===typeof c?c:c.type;l.log("[event] fire",e,c,a);if(f.hasOwnProperty(e))for(e=f[e],n=0;n<e.length;n+=1)k=e[n],g=k.method,"string"===typeof g&&(g=this[g]),k=b.extend(!0,{},k.argsObj,a),g.call(this,k);return this};c.on=function(b,a,c){l.log("[event] on",b,a,c);a={method:a,argsObj:c};f.hasOwnProperty(b)?f[b].push(a):f[b]=[a];return this};return c}}});"use strict";k.when("jQuery","logging","dv-register-once").register("av-widget-config",function(f,b,c){function l(b){g.debug(b);this.name=b}var g=
b.create("dv-widget-config",k);l.prototype={get:function(b){var c=f.parseJSON(f("#av-wconf-"+this.name).html());g.debug("widget: "+this.name,b,JSON.stringify(c));return"undefined"!==typeof b?c[b]:c}};return{declare:function(b){g.debug(b);c(b,new l(b))}}})});
/* ******** */
(function(a){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,b=d?d("DigitalVideoEpisodeListAssets"):c;b.guardFatal?b.guardFatal(a)(b,window):b.execute(function(){a(b,window)})})(function(a,c,d){a.when("A","jQuery","ready").execute(function(b,a){a("body").delegate(".dv-el-title","click",function(b){b.stopImmediatePropagation();589>a(c).width()&&a(this).closest(".dv-episode-container").toggleClass("dv-el-opened")})})});
/* ******** */
(function(c){var z=window.AmazonUIPageJS||window.P,J=z._namespace||z.attributeErrors,h=J?J("DigitalVideoWebPurchasingAssets"):z;h.guardFatal?h.guardFatal(c)(h,window):h.execute(function(){c(h,window)})})(function(c,z,J){c.when("A","logging","dv-pp-pin-view","aiv-util-event","dv-async").register("dv-pp-pin-controller",function(h,e,k,g,f){var b=e.create("dv-pp-pin-controller"),a=f.create("dv-pp-pin-controller",c),q=h.$,x={strings:{CHECKING_PIN:"Checking Pin...",PIN_INVALID:"The Pin you have entered is invalid, please try again.",
AUTHENTICATION_SUCCESS:"Authentication successful.",AUTHENTICATION_FAILURE:"This pin is not correct, please try again",TOKEN_FAILURE:"Your session has expired, please refresh the page and try again.",BAD_REQUEST:"We had a problem validating your pin, please refresh the page and try again"},urls:{pinCheckUrl:"/gp/video/usdvm/ajax/show_parental_dialog.html",pinAuthUrl:"/gp/video/usdvm/ajax/pin-check.html"},action:"PURCHASE",validationPeriod:1E3,successMsgDuration:200,isTestRun:!1,numPins:5,view:{pinConfig:{numPins:5},
events:{submit:"submitPin",show:"show",hide:"hide",cancel:"cancel",close:"close"}}};return{create:function(f,w){function l(d,m){u.fire(d,m)}function c(){var d=v.getUserPin();(new RegExp("^\\d{"+r.numPins+"}$")).test(d)?(v.createMessage("info",r.strings.CHECKING_PIN),B(d)):(v.createMessage("error",r.strings.PIN_INVALID),v.resetPin())}function e(){var d=p.activeAsin;H(d)?D(d):(delete m[d],l("pinAuthFailure",{asins:d}));delete p.activeAsin}function y(d,a,p){b.debug(d,a,p);d&&(a||(a="UNAUTHORIZED"),m[d]=
I(a,p))}function I(d,a){var m=(new Date).getTime(),p=m+r.validationPeriod;return{getStatus:function(){return d},getTimestamp:function(){return m},isExpired:function(){return p<(new Date).getTime()},getToken:function(){return a}}}function C(d){b.debug(d);if(d)return m[d]||n(d),m[d]}function H(d){b.log("[DV PIN] isAuthorized",d);if(!d)return!1;E(d);return"AUTHORIZED"===C(d).getStatus()&&E(d)?!0:!1}function D(d){var a=C(d);b.log("[DV PIN] handleAsinAuthorization",d,a.getStatus());switch(a.getStatus()){case "ERROR":l("pinAuthFailure",
{asins:d});y(d,"UNAUTHORIZED");break;case "TOKEN_INVALID":l("sessionExpired",{asins:d});y(d,"UNAUTHORIZED");break;case "AUTHORIZED":E(d)?l("success",{asins:d,token:a.getToken()}):(y(d,"UNAUTHORIZED"),D(d));break;case "UNAUTHORIZED":v.trigger(r.view.events.show);p.activeAsin=d;break;case "PENDING":p.callbackHandleAuth=!0;break;default:b.log("[DV PIN] handleAsinAuthorization default",d,a),l("pinAuthFailure",{asins:d}),y(d,"UNAUTHORIZED")}}function E(d){d=C(d);return"AUTHORIZED"!==d.getStatus()?!1:d.isExpired()?
!1:!0}function F(d){d&&"function"===typeof d&&d()}function t(d){b.debug(d);a.ajax(d.url,{params:d.data,success:function(){d.success.apply(this,arguments);F(d.complete)}},{maxRetrys:3,customError:function(a,m,p){l("error");F(d.error);F(d.complete)}})}function B(d){b.debug(d);t({url:r.urls.pinAuthUrl,data:{csrfToken:r.csrfToken,pin:d,asin:p.activeAsin},type:"jsonp",success:G,error:function(){v.createMessage("error",r.strings.AUTHENTICATION_FAILURE)}})}function G(d){var a=p.activeAsin,m;b.log("[DV PIN] performPinAuthenticationSuccess",
d);if(d.success)v.createMessage("success",r.strings.AUTHENTICATION_SUCCESS),y(a,"AUTHORIZED",d.token),v.trigger(r.view.events.hide,{delay:r.successMsgDuration});else{switch(d.error){case "INVALID_CSRF_TOKEN":m=r.strings.TOKEN_FAILURE;break;case "BAD_REQUEST":m=r.strings.BAD_REQUEST;break;case "WRONG_PIN":case "INCORRECT_PIN_FORMAT":m=r.strings.AUTHENTICATION_FAILURE}v.createMessage("error",m);v.resetPin()}}function n(d){y(d,"PENDING");b.log("[DV PIN] performPinRequiredCheck",d);t({url:r.urls.pinCheckUrl,
data:{ASINS:d,csrfToken:r.csrfToken,action:r.action},asin:d,complete:function(){b.log("[DV PIN] performPinRequiredCheck complete",p);p.callbackHandleAuth&&(p.callbackHandleAuth=!1,D(d));l("pinRequiredCheckComplete")},success:function(a){b.log("[DV PIN] performPinRequiredCheck success",a);var m="UNAUTHORIZED";(p.data=a)&&"object"===typeof a&&("BAD_REQUEST"===a.error?m="ERROR":"TOKEN_INVALID"===a.error?m="TOKEN_INVALID":a.pinRequired?(m="UNAUTHORIZED",a=a.numPinsRequired,b.debug(a),a&&(r.numPins=a,
v.setNumViewPins(a))):m="AUTHORIZED");y(d,m)}})}var u={},v,r={},m={},p={};b.log("[DV-PURCH] pin-controller");(function(d,a){b.debug(d,a);q.extend(!0,r,x,d);v=r.isTestRun&&a?a:k.create(r.view);g.bestowEvents(u);v.on(r.view.events.submit,c);v.on(r.view.events.close,e);h.on("dv:purchase:cancel",function(d){delete m[d.asins];delete p.activeAsin})})(f,w);return{on:function(d,a){u.on([d],a)},trigger:l,isAuthorized:H,performPinRequiredCheck:n,getAsinStatus:C,handleAsinAuthorization:D}}}});c.when("A","jQuery",
"logging","aiv-util-event","aiv-modal","aiv-alerts").register("dv-pp-pin-view",function(c,e,k,g,f,b){var a=k.create("dv-pp-pin-view"),q={focusFieldsOnKeyUp:!0,id:"dv-purchase-pin-view",isIosDevice:!1,selectors:{modalSelector:"#dv-pin-pop",pinWrap:"#pin-wrap",continueButton:"#dv-purchase-pin-view-submit",cancelButton:"#dv-purchase-pin-view-cancel",statusMsg:".dv-pin-pop-status-msg"},selectorFragments:{submitSuffix:"-submit"},hasCustomConfig:!1,pinConfig:{numPins:5,numPinInputs:void 0,pinInputParams:{pattern:"[0-9]*",
type:"password",size:"1",maxlength:"1","class":"pinNum"}},events:{submit:"submitPin",show:"show",hide:"hide",close:"close"}};return{create:function(x){function A(b,m){a.log("[PIN-VIEW] trigger",b);G.fire(b,m)}function w(){var b=document.createElement("input"),m=t.pinConfig.pinInputParams,p;a.log("[PIN-VIEW] createInputElem",m);for(p in m)m.hasOwnProperty(p)&&b.setAttribute(p,m[p]);return b}function l(b){a.log("[PIN-VIEW] buildUpPopover",b);v=b.popover;n.$popover=v.$popover;b=n.$popover.find("input.pinNum");
if(!b||!b.length){var m=n.$popover.find(t.selectors.pinWrap),p=t.pinConfig.numPinInputs||t.pinConfig.numPins;a.log("[PIN-VIEW] appendInputs",t);for(b=1;b<=p;b+=1)m.append(w());n.$pins=m.find("input");a.log("[PIN-VIEW] registerEventHandlers");n.$submit=e("#"+u.name+t.selectorFragments.submitSuffix);n.$submit.find("input").click(C);t.focusFieldsOnKeyUp&&(n.$pins.keyup(y),n.$pins.keydown(z))}E()}function k(){a.log("[PIN-VIEW] tearDownPopover",n.$popover);A(t.events.close);F();n.$pins&&n.$pins.remove();
n.$popover&&n.$popover.find("input").unbind();B.submitDisabled=!1;delete n.$popover}function z(b){var m=e(this);b=8===b.which;a.log("[PIN-VIEW] handleKeyDown");b&&((b=0<m.val().length)||m.prev("input").focus().val(""))}function y(b){var m=e(this),p=m.not().is(":last-child"),d=0<m.val().length;b=13===b.which;var l=D().length===t.pinConfig.numPins;a.log("[PIN-VIEW] handleKeyUp");l?B.submitDisabled&&(n.$submit.removeClass("a-button-disabled").find("input").removeAttr("disabled"),B.submitDisabled=!1):
I();b&&l?C():!d||p||l||m.next().focus();B.messageVisible&&F()}function I(){B.submitDisabled||(n.$submit.addClass("a-button-disabled").find("input").attr("disabled","disabled"),B.submitDisabled=!0)}function C(){a.log("[PIN-VIEW] handleSubmit");A(t.events.submit)}function H(b){a.log("[PIN-VIEW] hide",u,b);b&&b.delay?c.delay(function(){u.remove()},b.delay):u.remove()}function D(){var a=[];n.$pins.each(function(b,p){p.value.length&&(1<p.value.length?a=p.value.split(""):a.push(p.value))});return a}function E(){a.log("[PIN-VIEW] resetPin");
n.$pins.val("");c.delay(function(){n.$pins.first().focus()},10);I()}function F(){B.messageVisible=!1;n.$popover&&n.$popover.find(t.selectors.statusMsg).html("")}var t={},B={},G={},n={},u,v;a.log("[PIN-VIEW]");e.extend(!0,t,q,x);a.log("[PIN-VIEW] init",t);g.bestowEvents(G);a.log("[PIN-VIEW] registerCustomEvents");G.on(t.events.show,function(){a.log("[PIN-VIEW] show",u);u=f.create({selector:t.selectors.modalSelector,id:t.id});a.log("[PIN-VIEW] registerAUIModalHandlers");u.on("afterShow",l);u.on("afterHide",
k);u.on("dv:dv-modal:cancel",H);u.show()});G.on(t.events.hide,H);return{getUserPin:function(){return D().join("")},on:function(b,m){a.log("[PIN-VIEW] on",b);G.on([b],m)},trigger:A,createMessage:function(a,m){var p;b[a]&&typeof("function"===b[a])&&(p=b[a](m,"inline","light"),F(),n.$popover.find(t.selectors.statusMsg).html(p),B.messageVisible=!0)},resetPin:E,setNumViewPins:function(a){a&&(t.pinConfig.numPins=a,t.hasCustomConfig?(t.pinConfig.pinInputParams.size=a,t.pinConfig.pinInputParams.maxlength=
a):t.pinConfig.numPinInputs=a)}}}}});c.when("A","jQuery","logging","promise-pipeline","purchase-modal").register("dv-hd-warning",function(h,e,k,g,f){function b(a,b,q){return function(){f.create({id:a,asin:q,deferred:b,continuePurchaseOnSubmit:!0,cancelPurchaseOnCancel:!0,urlParameters:{asin:q}}).show()}}var a=k.create("dv-hd-warning",c),q;c.when("dv-web-player-capabilities").execute(function(b){b(function(b){a.log("[DV-PURCH] hd-warning playerCapabilities",b);q=b.capabilities})});return g.step("dv-hd-warning",
function(f,c){var e,l,g;a.debug("[DV-PURCH] hd-warning",c,q);q&&(l=q.supportsWebPlayback,g=q.supportsHDMovies);a.debug("supportsWebPlayback:",l,"supportsHDMovies:",g);e={showHDWarning:b("dv-modal-hd-content-warning",f,c.asin),showHDCPWarning:b("dv-modal-hdcp-content-warning",f,c.asin),showUnsupportedWarning:b("dv-modal-unsupported-device-warning",f,c.asin),continuePurchase:f.resolve};l?g?c.canShowWebHdcpWarning?e.showHDCPWarning():e.continuePurchase():c.canShowWebHdWarning?e.showHDWarning():e.continuePurchase():
c.showUnsupportedWarning?e.showUnsupportedWarning():c.showDeviceHdWarning?e.showHDWarning():c.showDeviceHdcpWarning?e.showHDCPWarning():e.continuePurchase()},c)});c.when("jQuery","logging","promise-pipeline").register("dv-sign-in",function(h,e,k){e.create("dv-sign-in",c);return k.step("dv-sign-in",function(c,f){f.shouldSignIn?z.location.replace(f.signInUrl):c.resolve()},c)});c.when("A","jQuery","logging","promise-pipeline","purchase-modal","dv-age-verification-data-ready").register("dv-age-verification",
function(h,e,k,g,f){var b=k.create("dv-age-verification",c);return g.step("dv-age-verification",function(a,c){var e=h.state("dv-age-verification-data");b.log("[DV-PURCH] dv-age-verification",c,e);e&&e.isAgeVerificationRequired?f.create({id:"dv-age-verification-modal",asin:c.asin,deferred:a}).show():a.resolve()},c)});c.when("A","jQuery","logging","promise-pipeline","dv-pp-pin-controller","purchase-modal","dv-purchasing-errors").register("dv-pin-verification",function(h,e,k,g,f,b,a){var q=k.create("dv-pin-verification",
c);return g.step("dv-pin-verification",function(b,c){var e=c.pinVerification,l=f.create(e);q.log("[DV-PURCH] pin-verification",e,c);l.on("success",function(a){q.log("Pin Check Success happened with args:",a);b.resolve(a)});l.on("pinAuthFailure",function(a){q.log("Pin Check Failure happened with args:",a);b.reject({reload:!1})});l.on("sessionExpired",function(l){q.log("Pin Check Failure happened with args:",l);b.reject({errors:[a.invalidCSRFToken()],reload:!1})});l.handleAsinAuthorization(c.asin)},
c)});c.when("A","jQuery","logging","promise-pipeline","purchase-call-handler").register("dv-create-order",function(h,e,k,g,f){k.create("dv-create-order",c);return g.step("dv-create-order",function(b,a){var c={deferred:b,endpoint:a.createOrder&&a.createOrder.url,callData:a.purchaseArgs||{},asins:a.asin,ajaxDataType:a.ajaxDataType,purchasingModalText:a.purchasingModalText},e=a.token;e&&(c.callData.pinToken=e);f.create(c).callPurchase()},c)});c.when("A","jQuery","logging","promise-pipeline","purchase-call-handler").register("dv-check-order-status",
function(h,e,k,g,f){k.create("dv-check-order-status",c);return g.step("dv-check-order-status",function(b,a){var c={deferred:b,endpoint:a.checkOrderStatus&&a.checkOrderStatus.url,callData:a.purchaseArgs,asins:a.asin,ajaxDataType:a.ajaxDataType,purchasingModalText:a.purchasingModalText};a.token&&(c.callData.pinToken=a.token);a.orderToken&&(c.callData.orderToken=a.orderToken);f.create(c).callPurchase()},c)});c.when("A","jQuery","logging","dv-async","dv-purchase-fix-up","aiv-client-side-metrics").register("purchase-call-handler",
function(h,e,k,g,f,b){var a=k.create("purchase-call-handler",c),q=g.create("purchase-call-handler",c),x={endpoint:"/gp/video/order/create-order.html",ajaxDataType:"jsonp",ajaxRetries:3,callData:void 0,jsonpCallback:void 0,isOrderStatusCheck:!1},A=b.create({scope:"dvweb-buybox-purchase"}),w=b.create({scope:"dvweb-buybox-orderAction"}),l=b.create({scope:"dvweb-buybox-polling"});return{create:function(b){function c(b){var e=b.action||{},x=b.orderToken;e.deferred=h.deferred;x&&(h.callData.orderToken=
x);a.log("[ajaxPurchase] _ajaxSuccess",navigator.userAgent,b);switch(b.status){case "SUCCESS":h.isOrderStatusCheck?(w.ajaxSuccess({requestId:b.requestId}),w.ajaxDone()):(A.ajaxSuccess({requestId:b.requestId}),A.ajaxDone());h.deferred.resolve({orderToken:b.orderToken});break;case "PENDING":l.counter("dvweb-checkOrderStatus-polling");q.delay(k,e.delay);break;case "ERROR":f.fix(g(e));break;default:f.fix(e)}}function g(a){h.purchasingModalText&&a.modal&&a.modal.header&&a.modal.header.text&&(a.modal.header.text=
a.modal.header.text+" "+h.purchasingModalText);return a}function k(){var b={params:h.callData,success:c,jsonpCallback:h.jsonpCallback},l={maxRetrys:h.ajaxRetries,customError:function(b,c,l){a.error(c,l);h.deferred&&h.deferred.reject()}};A.ajaxStart();q.ajax(h.endpoint,b,l)}var h={};e.extend(!0,h,x,b);a.log("[ajaxPurchase] create",h);return{callPurchase:function(){k()}}}}});c.when("A","jQuery","logging","purchase-modal").register("dv-purchase-fix-up",function(c,e,k,g){var f=k.create("dv-purchase-fix-up");
return{fix:function(b){f.log("[fixUp] errorAction:",b);b||(f.error("no action was passed to errorAction"),b={});b.deferred&&!b.redirectUrl&&b.deferred.reject();b.modal?(f.log("[fixUp] _actionModal:",b),b.modal&&(b.modal.deferred=b.deferred,g.create(b.modal).show())):b.redirectUrl?(f.log("[fixUp] _actionRedirect args:",b),z.location.href=b.redirectUrl):(f.log("[fixUp] _generalError args:",b),g.create({id:"dv-modal-generic-error",cancelPurchaseOnSubmit:!0,deferred:b.deferred}).show())}}});c.when("A",
"jQuery","logging","aiv-modal").register("purchase-modal",function(c,e,k,g){function f(a,e){var f=a.getName(),g=e.deferred;c.on("a:popover:beforeHide:"+f,function(a){b.log("a:popover:beforeHide:"+f+" happened",a,g);g&&g.reject({reload:!1})});a.on("submit",function(c){b.log("[DV-PURCH] purchase-modal submit",c,g);g&&g.resolve();a.remove()});a.on("link",function(c){b.log("[DV-PURCH] purchase-modal link",c,g);var l=c.url;l?z.location.href=l:b.error("purchaseModal link event called without url",c);a.remove()});
a.on("cancel",function(c){b.log("[DV-PURCH] purchase-modal cancel",c,g);g&&g.reject({reload:!1});a.remove()})}var b=k.create("purchase-modal");return{create:function(a){var c={cancel:{customEvent:"cancel",eventArgs:{asin:a.asin,id:a.id,cancelPurchaseOnCancel:"undefined"!==typeof a.cancelPurchaseOnCancel?a.cancelPurchaseOnCancel:!0}},submit:{customEvent:"submit",eventArgs:{asin:a.asin,id:a.id,continuePurchaseOnSubmit:a.continuePurchaseOnSubmit,retryPurchaseOnSubmit:a.retryPurchaseOnSubmit,cancelPurchaseOnSubmit:a.cancelPurchaseOnSubmit}},
checked:{customEvent:"checked",eventArgs:{id:a.id,elemId:a.id+"-check"}}},h;h=(h=e("#"+a.id).data("dv-modal"))&&h.buttons||[];var k={},w,l;for(w=0;w<h.length;w++)l=h[w].type,k[l]=h[w];c=e.extend(!0,{},c,k);c=e.extend(!0,{},{showCloseButton:!1,footer:{},buttons:[c.cancel,c.submit,c.checked]},a);b.log("purchase-modal createModal with options",c);c=g.create(c);f(c,a);return c}}});c.when("dv-sign-in","dv-age-verification","dv-hd-warning","dv-pin-verification","dv-create-order","dv-check-order-status").register("purchase-pipeline",
function(c,e,k,g,f,b){return{start:function(){return[c,e,k,g,f,b]},continuePurchase:function(){return[c,b]}}});c.when("jQuery","logging","aiv-modal").register("dv-purchasing-errors",function(h,e,k){function g(a){this.name="MissingAsin";this.message=a;this.stack=Error().stack}function f(a){this.name="MissingPinToken";this.message=a;this.stack=Error().stack}function b(a){this.name="MissingCSRFToken";this.message=a;this.stack=Error().stack}function a(a){this.name="InvalidCSRFToken";this.message=a;this.stack=
Error().stack}function q(a){this.name="MissingOrderToken";this.message=a;this.stack=Error().stack}function x(a){var b=k.create({id:"dv-modal-session-expired"}).show();w.error(a.message,a.stack);b.on("dv:dv-modal:submit",function(){document.location.reload(!0)})}function A(a){var b=k.create({id:"dv-modal-generic-error"}).show();w.error(a.message,a.stack);b.on("dv:dv-modal:submit",function(){document.location.reload(!0)})}var w=e.create("dv-purchase-errors",c);return{handleError:function(b){b&&(w.log("_handleError",
b),b instanceof a?x(b):A(b))},invalidCSRFToken:function(b){return new a(b)},missingAsin:function(a){return new g(a)},missingPinToken:function(a){return new f(a)},missingCSRFToken:function(a){return new b(a)},missingOrderToken:function(a){return new q(a)}}});c.when("A","logging","promise-pipeline","aiv-modal","dv-purchasing-errors","purchase-pipeline").register("purchase-video",function(h,e,k,g,f,b){function a(a,b){q.log("[DV-PURCH] purchase",a);var e=k.create({promises:b,options:a},"purchase-video",
c);e.done(function(a){q.log("[DV-PURCH] pipeline has finished",a)});e.fail(function(a){q.log("[DV-PURCH] pipeline has failed",a);a&&a.errors&&h.each(a.errors,function(a){f.handleError(a,c)})});return e}var q=e.create("purchase-video",c);return{start:function(c){q.log("[DV-PURCH] start",c);return a(c,b.start())},continuePurchase:function(c){q.log("[DV-PURCH] continue",c);return a(c,b.continuePurchase())}}});c.when("A","jQuery","logging","dv-purchase-data-ready").register("dv-purchase-continue",function(c,
e,k){var g=k.create("dv-purchase-continue");return{checkPurchaseTriggers:function(){g.log("[purchase] checkPurchaseTriggers");var f=e.Deferred(),b=c.state("dv-purchase-continue-data")||{},a=b.purchaseAsin,k=b.purchaseToken,x=b.orderToken;g.log("[purchase] checkPurchaseTriggers state",a,k,x);a&&(k||x)&&e.ajax({url:b.validateTokenUrl,data:{purchasetoken:k},success:function(b){g.log("[purchase] validateActionToken success",b);b.success&&f.resolve({orderToken:x,asin:a})},error:function(a){g.log("[purchase] validateActionToken error",
a);f.reject(a)},dataType:"json"});return f.promise()}}});c.when("A","jQuery","logging","dv-form","dv-ux","dv-ux-mixins","dv-buttons","dv-utilities","dv-purchase-continue","purchase-video","dv-purchase-data-ready").register("dv-purchase-view",function(h,e,k,g,f,b,a,q,x,A){function w(a,b){h.trigger("aiv:modal:close:declarative");n.log(b);n.log(b);var d=b.isSeasonPurchase?e(u.actionBoxContainer):a.parents(u.actionBoxContainer);b.isSeasonPurchase?(H(d.siblings(".dv-el-status-wrapper")),f.hideContent(d.siblings(".dv-el-more-offers"))):
C(b.asin,f.hideContent);F(d,b);d=b.asin;n.log(d);d=I(d);H(d);b.orderToken?(n.log(b),d=A.continuePurchase(b)):(n.log(b),d=A.start(b));J(d)}function l(a){var b=a.parents("form"),b=g.data(b),d=h.state("dv-purchase-data")||{};a=a.find("input").data();return e.extend(!0,{},d,a,{asin:b.asin,pinVerification:{csrfToken:b.csrfToken},purchaseArgs:b})}function z(a){var b=h.state("dv-purchase-view-data")||{};return a?b[a]:b}function J(a){a.done(function(a){n.log("p.done",a);t(a)});a.fail(function(a){n.log("p.fail",
a);t(a)})}function y(a,b){return e(a).filter(function(a,c){return!!e(c).find("[data-asin\x3d"+b+"]")[0]})}function I(a){var b;a=q.getElemByAlias(u.episode,a);a.length&&(b=a.find(".dv-el-status-wrapper"));return b}function C(a,b){var d;d=q.getElemByAlias(u.episode,a);d.length&&b(d.find(".dv-el-more-offers"))}function H(a){a&&a.length&&a.each(function(a,b){f.hideContent(e(b));f.addSpinner(e(b))})}function D(a){a&&a.length&&a.each(function(b,d){f.showContent(a);f.removeSpinner(a)})}function E(a){n.log(a);
if(a=I(a))f.showContent(a),f.removeSpinner(a)}function F(a,c){n.log(a,c);a.length&&a.each(function(a,m){var f=e(m),g=f.hasClass("js-dv-action-box-episode"),f=b.extendable(f),h=e("\x3cp /\x3e").html(c.purchasingText),k=g?{}:{theme:"dark"},g=!(c.isSeasonPurchase&&g);f.addBehaviours(b.interactive,b.spinner);var l=c.asin;"undefined"!==typeof f&&(r[l]=r[l]||[],r[l].push(f));f.disable({disableOpacity:0}).addSpinner(k);g&&f.getSpinnerWrapper().value().append(h)})}function t(a){!1===a.reload?G(a.asin,a.isSeasonPurchase):
B(a)}function B(a){var b=a.purchaseArgs.asin,d=z("pageAsin"),e=q.getElemByAlias(u.episode,b),f=e.attr("id"),g=y(u.mainActionBox,b),k=!!g.length,l=!!e.length,t=a.isSeasonPurchase,r;n.log("resetActionBoxess",a,g,e);c.when("dv-ajax-reload").execute(function(a){var c=(h.state("dv-purchase-data")||{}).widgetRefresh.endpoint;k&&a.getWidgets({asin:d,url:c,loggingName:"dvweb-actionbox-purchase",widgets:["dv-action-box"]});t&&b?r=a.getWidgets({asin:d,url:c,loggingName:"dvweb-season-purchase",widgets:["dv-episode-list"]}):
l&&b&&(r=a.getWidgets({asin:b,url:c,loggingName:"dvweb-episodelist-purchase",widgets:["dv-el-offers","dv-el-more-offers","dv-el-cancel-order","js-ajaxable-episode-status"],DOMRootID:f}));r&&r.done(function(){E(b)})})}function G(c,g){n.log(c,g);var d=g?e(u.actionBoxContainer):y(u.actionBoxContainer,c);d.length&&d.each(function(c,d){var f=e(d),g=f.find(".js-dv-processing");b.extendable(f,b.interactive,b.spinner).removeSpinner().enable();a.resetButtonsOriginalState(g)});g?(D(d.siblings(".dv-el-status-wrapper")),
f.showContent(d.siblings(".dv-el-more-offers"))):(C(c,f.showContent),E(c))}var n=k.create("dv-purchase-view",c),u={mainActionBox:"#dv-action-box",actionBoxContainer:".js-dv-action-box, .js-dv-action-box-episode",actionBoxWrap:".js-dv-action-box-wrap",purchaseButton:".js-purchase-button",episode:".dv-episode-container"},v=h.capabilities.touch,r={};x.checkPurchaseTriggers().done(function(a){var b=y(u.purchaseButton,a.asin);if(0!=b.length){var c=b.first(),c=l(c);n.log(a);a.orderToken&&(c.orderToken=
a.orderToken);w(b,c)}});e("body").delegate(u.purchaseButton,"click",function(b){var c=e(this),c=l(c),d=c.asin;n.log(c);d=y(u.purchaseButton,d);d.hasClass("js-dv-processing")?(n.info("canceled",d),b.preventDefault(),b.stopImmediatePropagation()):(d.hasClass("dv-confirm")||!v?w(d,c):v&&(a.resetConfirmButtons(),a.addConfirmState(d,z("confirmButtonText")),b.stopPropagation()),b.preventDefault())})});c.when("A","logging").register("dv-order-cancellation",function(h,e){var k=e.create("dv-order-cancellation",
c);h.on("cancel-order:dv-self-cancel-modal:submit",function(){k.log("cancel-order:dv-self-cancel-modal:submit");c.when("a-dropdown").execute(function(c){var e=c.getSelect("dv-self-refund-drop-down").val().split(":",2);c=e[0];var e=e[1],b=h.$(".dvSelfCancelModal"),a=b.data("orderCancelBaseUrl"),b=b.data("pageAsin");k.log("orderCancelation",c,e,a);c&&e&&a&&(document.location.href=a+"?orderId\x3d"+c+"\x26asin\x3d"+e+"\x26return_to\x3d/gp/product/"+b)})})})});
/* ******** */
(function(n){var k=window.AmazonUIPageJS||window.P,y=k._namespace||k.attributeErrors,a=y?y("DigitalVideoHoverAssets"):k;a.guardFatal?a.guardFatal(n)(a,window):a.execute(function(){n(a,window)})})(function(n,k,y){n.when("jQuery").register("borderWidthPlugin",function(a){a.fn.getBorderWidth=function(){var k=this,h=a.unique(a.map(["bottom","top","left","right"],function(a){return k.css("border-"+a+"-width")}));if(1<h.length)throw Error("The element doesn't have the same width on each of its side.");
return h[0]}});n.when("A","hoverPositionCalculator","ready").execute(function(a,n){var h=a.$,p,b,l=null,d=null,c=k.uet,e=k.ues,g=k.uex,v=k.ue,f=[],r={hideTimer:null,titleID:null,finalPositionSet:!1,recordEvent:function(a,b){a&&("function"===typeof c&&c(b,a,{wb:1}),f.push(b),2===f.length&&("af"===f[0]&&v.count(a+":spinner",1),"function"===typeof g&&g("ld",a,{wb:1})))},chunkHandler:function(a){(!a||a.length)&&"hover-body"===a[0]&&d&&d.append(h(a[1]))},getHoverAllowedArea:function(){var a=h(k),b=h("#av-nav.av-nav.av-blur-backdrop").outerHeight()||
0,l=h(".a-section.dv-standard-carousel .dv-carousel, #aiv-cl-main-middle").first(),b=a.scrollTop()+b,a=a.scrollTop()+a.height(),d=l.offset().left,l=d+l.outerWidth();return{top:b,left:d,bottom:a,right:l}},getSkin:function(){return'\x3csection id\x3d"av-hover" class\x3d"av-narrow av-hover av-popover"\x3e\x3cspan id\x3d"arrow-hover"\x3e\x3cspan id\x3d"arrow"\x3e\x3c/span\x3e\x3c/span\x3e\x3cdiv class\x3d"av-spinner"\x3e\x3c/div\x3e\x3c/section\x3e'},setPosition:function(a,b){if(!this.finalPositionSet){var l=
h("#av-hover"),d=l.children("#arrow-hover"),c=d.children("#arrow"),e=l.children(".av-spinner");if(l.length&&c.length){e.css({"margin-top":80,"margin-bottom":80});var e=this.getHoverAllowedArea(),f=a.offset(),f={top:f.top,left:f.left,bottom:f.top+a.outerHeight(),right:f.left+a.outerWidth(),height:a.outerHeight(),width:a.outerWidth()},g={height:l.outerHeight(),width:l.outerWidth()},e=n.calculatePosition(f,g,e),f=n.calculateArrowPosition(f,{top:e.hoverPosition.top,left:e.hoverPosition.left,width:g.width,
height:g.height},e.orientation,{height:12,base:16},l.css("border-width"));l.css(e.hoverPosition).removeClass("av-hover-top").removeClass("av-hover-left").removeClass("av-hover-right").removeClass("av-hover-bottom").addClass("av-hover-"+e.orientation).data("ps",a).fadeIn();d.css(f.arrowHoverPosition);c.css(f.arrowPosition).removeClass("arrow-top").removeClass("arrow-left").removeClass("arrow-right").removeClass("arrow-bottom").addClass(f.arrowClass).fadeIn();this.recordEvent(b,"af")}else this.hide()}},
show:function(g){var m=this,r=null;clearTimeout(p);clearTimeout(b);null!==m.hideTimer&&clearTimeout(m.hideTimer);f=[];l&&l.abort();m.finalPositionSet=!1;d=h("body");d.append(m.getSkin());p=setTimeout(function(){var d="dv-av-hover"+("downloadable_movie"===g.data("type")?"-movie":"-tv");"function"===typeof c&&"function"===typeof e&&(e("t0",d,new Date),c("bb",d,{wb:1}));var f=g.data("titleId")||g.data("asin"),p=k.location.pathname,v="/gp/video/hover/";p.match(/\/region\//)&&(v=p.replace(/(\/region\/\w{2})(.*?)+$/,
"$1/gp/video/hover/"));v+=f;b=setTimeout(function(){m.setPosition(g,d)},g.data("render-hover"));l=a.ajax(v,{method:"get",params:{format:"json"},accepts:"application/json-amazonui-streaming",timeout:1E4,chunk:m.chunkHandler,success:function(a){r=h("#av-hover-body").html();h("#av-hover-body").remove();h(".av-spinner").remove();h("#av-hover").append(r);m.titleID=f;m.setPosition(g);m.finalPositionSet=!0;m.recordEvent(d,"cf")},error:function(){m.hide()}})},g.data("ajax-request"))},hide:function(){l&&(l.abort(),
l=null);r.titleID=null;h("#av-hover").remove();h("#av-hover").stop(!0,!0).hide()}};h(".dark-hover-enabled").live("mouseenter",function(a){a=h(this);var b=a.data("titleId")||a.data("asin");h("#av-hover").length&&b===r.titleID||(h("#av-hover").length&&r.hide(),a.closest(".dv-standard-carousel").hasClass("dv-list-remove-item-highlight-selected")||r.show(a))}).live("mouseleave click",function(a){clearTimeout(p);h(a.relatedTarget).is("#av-hover")||h(a.relatedTarget).is("#arrow-hover")||(r.hideTimer=setTimeout(function(){r.hide();
clearTimeout(r.hideTimer)},200))});h("#av-hover").live("mouseenter",function(a){null!==r.hideTimer&&clearTimeout(r.hideTimer)}).live("mouseleave av-hide-hover",function(a){0>h(a.relatedTarget).parents().index(h(this).data("ps"))&&r.hide()});return r});n.register("hoverPositionCalculator",function(){function a(a){switch(a){case b.HoverOrientationTypes.Right:case b.HoverOrientationTypes.Left:return!0;case b.HoverOrientationTypes.Top:case b.HoverOrientationTypes.Bottom:return!1;default:throw"CalculateArrowPosition - Orientation value not expected: "+
a;}}function n(a,b,c){var e=Math.min(c?a.top+a.height:a.left+a.width,c?b.top+b.height:b.left+b.width);a=Math.max(c?a.top:a.left,c?b.top:b.left);return e-a}function h(b,d,c,e){var g=n(b,d,a(c));b=a(c)?Math.max(0,b.top-d.top):Math.max(0,b.left-d.left);return(g-e)/2+b}function p(a,d,c,e){var g;switch(a){case b.AxisTypes.Horizontal:g=d===b.HoverOrientationTypes.Right&&c.right>=e.width||d===b.HoverOrientationTypes.Left&&c.left>=e.width?d:c.bottom>=.9*e.height?b.HoverOrientationTypes.Bottom:c.top>=e.height-
b.hoverPaddingTop?b.HoverOrientationTypes.Top:c.bottom>=.7*e.height?b.HoverOrientationTypes.Bottom:c.right>=.7*e.width?b.HoverOrientationTypes.Right:c.left>=.85*e.width?b.HoverOrientationTypes.Left:c.right/e.width>=c.bottom/e.height?b.HoverOrientationTypes.Right:b.HoverOrientationTypes.Bottom;break;case b.AxisTypes.Vertical:g=d===b.HoverOrientationTypes.Bottom&&c.bottom>=e.height||d===b.HoverOrientationTypes.Top&&c.top>=e.height?d:c.right>=.7*e.width?b.HoverOrientationTypes.Right:c.left>=.85*e.width?
b.HoverOrientationTypes.Left:c.bottom>=.9*e.height?b.HoverOrientationTypes.Bottom:c.top>=e.height-b.hoverPaddingTop?b.HoverOrientationTypes.Top:c.bottom>=.7*e.height?b.HoverOrientationTypes.Bottom:c.right/e.width>=c.bottom/e.height?b.HoverOrientationTypes.Right:b.HoverOrientationTypes.Bottom}return g}var b={hoverPaddingTop:26,HoverOrientationTypes:{Top:"top",Bottom:"bottom",Left:"left",Right:"right"},AxisTypes:{Horizontal:"Horizontal",Vertical:"Vertical"},PackshotPlacementTypes:{WithinBounds:"WithinBounds",
OutOfBoundsTop:"OutOfBoundsTop",OutOfBoundsBottom:"OutOfBoundsBottom",OutOfBoundsLeft:"OutOfBoundsLeft",OutOfBoundsRight:"OutOfBoundsRight"}};return{computeIntersections:n,calculatePosition:function(a,d,c,e){var g,h,f;if(void 0===a||void 0===d||void 0===c)return{};a.bottom=a.bottom||a.top+a.height;a.right=a.right||a.left+a.width;g=0>a.left-c.left?b.PackshotPlacementTypes.OutOfBoundsLeft:0>c.right-a.right?b.PackshotPlacementTypes.OutOfBoundsRight:b.PackshotPlacementTypes.WithinBounds;h=0>a.top-c.top?
b.PackshotPlacementTypes.OutOfBoundsTop:0>c.bottom-a.bottom?b.PackshotPlacementTypes.OutOfBoundsBottom:b.PackshotPlacementTypes.WithinBounds;f={top:a.top-c.top,left:a.left-c.left,bottom:c.bottom-a.bottom,right:c.right-a.right};var k=f.right>=f.left?b.HoverOrientationTypes.Right:b.HoverOrientationTypes.Left,n=f.bottom>=f.top?b.HoverOrientationTypes.Bottom:b.HoverOrientationTypes.Top;if(h===b.PackshotPlacementTypes.WithinBounds)g=k===b.HoverOrientationTypes.Right&&f.right>=d.width||k===b.HoverOrientationTypes.Left&&
f.left>=d.width?k:p(b.AxisTypes.Vertical,n,f,d);else if(g===b.PackshotPlacementTypes.WithinBounds)g=n===b.HoverOrientationTypes.Bottom&&f.bottom>=d.height||n===b.HoverOrientationTypes.Top&&f.top>=d.height?n:p(b.AxisTypes.Horizontal,k,f,d);else{var m;h===b.PackshotPlacementTypes.OutOfBoundsTop?g===b.PackshotPlacementTypes.OutOfBoundsLeft?m=a.right-c.left>a.bottom-c.top?p(b.AxisTypes.Vertical,b.HoverOrientationTypes.Bottom,f,d):p(b.AxisTypes.Horizontal,b.HoverOrientationTypes.Right,f,d):g===b.PackshotPlacementTypes.OutOfBoundsRight&&
(m=c.right-a.left>a.bottom-c.top?p(b.AxisTypes.Vertical,b.HoverOrientationTypes.Bottom,f,d):p(b.AxisTypes.Horizontal,b.HoverOrientationTypes.Left,f,d)):h===b.PackshotPlacementTypes.OutOfBoundsBottom&&(m=g===b.PackshotPlacementTypes.OutOfBoundsLeft?a.right-c.left>c.bottom-a.top?p(b.AxisTypes.Vertical,b.HoverOrientationTypes.Top,f,d):p(b.AxisTypes.Horizontal,b.HoverOrientationTypes.Right,f,d):c.right-a.left>c.bottom-a.top?p(b.AxisTypes.Vertical,b.HoverOrientationTypes.Top,f,d):p(b.AxisTypes.Horizontal,
b.HoverOrientationTypes.Left,f,d));g=m}a:switch(g){case b.HoverOrientationTypes.Right:h=a.right;f=a.top-b.hoverPaddingTop;break a;case b.HoverOrientationTypes.Left:h=a.left-d.width;f=a.top-b.hoverPaddingTop;break a;case b.HoverOrientationTypes.Top:h=a.left+(a.width-d.width)/2;f=a.top-d.height;break a;case b.HoverOrientationTypes.Bottom:h=a.left+(a.width-d.width)/2;f=a.bottom;break a;default:throw"GetHoverPosition - Orientation value not expected: "+g;}d.left=h;d.top=f;if(void 0===c||void 0===a||void 0===
d||g!==b.HoverOrientationTypes.Left&&g!==b.HoverOrientationTypes.Right&&g!==b.HoverOrientationTypes.Top&&g!==b.HoverOrientationTypes.Bottom)a={};else{switch(g){case b.HoverOrientationTypes.Right:case b.HoverOrientationTypes.Left:d.top=Math.min(d.top,c.bottom-d.height);d.top=Math.max(d.top,c.top);a.top-b.hoverPaddingTop>d.top&&c.top<d.top&&a.top+a.height<d.top+d.height&&(d.top=Math.max(c.top,d.top-(d.top+d.height-(a.top+a.height))));break;case b.HoverOrientationTypes.Top:case b.HoverOrientationTypes.Bottom:d.orientation===
b.HoverOrientationTypes.Top&&(d.top=Math.min(d.top,a.top-d.height)),d.left=Math.min(d.left,c.right-d.width),d.left=Math.max(d.left,c.left)}a={left:d.left,top:d.top}}if(e)switch(g){case b.HoverOrientationTypes.Right:a.left+=e;break;case b.HoverOrientationTypes.Left:a.left-=e;break;case b.HoverOrientationTypes.Top:a.top-=e;break;case b.HoverOrientationTypes.Bottom:a.top+=e}return{hoverPosition:a,orientation:g}},calculateArrowPosition:function(l,d,c,e,g){if(void 0===l||void 0===d||c!==b.HoverOrientationTypes.Left&&
c!==b.HoverOrientationTypes.Right&&c!==b.HoverOrientationTypes.Top&&c!==b.HoverOrientationTypes.Bottom||"undefined"===typeof e)return{};g=g?2*k.parseFloat(g):0;var n=0,f=0,p,z,m=0,u=0;a(c)?(z=d.height,p=e.height,f=h(l,d,c,e.base)):(p=d.width,z=e.height,n=h(l,d,c,e.base));switch(c){case b.HoverOrientationTypes.Right:l="arrow-left";m=-1*e.height;break;case b.HoverOrientationTypes.Left:l="arrow-right";m=d.width-g;break;case b.HoverOrientationTypes.Top:l="arrow-bottom";u=d.height-g;break;case b.HoverOrientationTypes.Bottom:l=
"arrow-top";u=-1*e.height;break;default:throw"CalculateArrowPosition - Orientation value not expected: "+c;}return{arrowPosition:{left:n,top:f},arrowHoverPosition:{left:m,top:u,width:p,height:z},arrowClass:l}}}});n.when("jQuery","hoverPositionCalculator","borderWidthPlugin","ready").execute(function(a,y){function h(q,b,d,c){q={bottom:b.top+q.outerHeight(),height:q.outerHeight(),left:b.left,right:b.left+q.outerWidth(),top:b.top,width:q.outerWidth()};b=a(k);d=a(".a-section.dv-standard-carousel .dv-carousel, #aiv-cl-main-middle").first();
var e=d.offset().left+d.outerWidth(),e=b.width()<e?b.width():e;d={top:b.scrollTop(),left:d.offset().left,bottom:b.scrollTop()+b.height(),right:e};b={height:a("#universal-hover").outerHeight(),width:a("#universal-hover").outerWidth()};d=y.calculatePosition(q,b,d,10);a("#universal-hover").css({left:d.hoverPosition.left,top:d.hoverPosition.top}).data("ps",c).fadeIn();c=y.calculateArrowPosition(q,{top:d.hoverPosition.top,left:d.hoverPosition.left,width:b.width,height:b.height},d.orientation,{height:12,
base:21},a("#universal-hover").getBorderWidth());q=a("#universal-hover").children("#arrow-hover");b=q.children("#arrow");q.css(c.arrowHoverPosition);b.css(c.arrowPosition).removeClass("arrow-top").removeClass("arrow-left").removeClass("arrow-right").removeClass("arrow-bottom").addClass(c.arrowClass).fadeIn()}function p(q){var d=q.offset(),c=a(k);c.height();c.width();c.scrollTop();c.scrollLeft();a("#player_object").length||a("#dv-dp-player-content").css("opacity");clearTimeout(z);clearTimeout(m);u&&
u.abort();var e="dv-universal-hover",e="downloadable_movie"===q.data("type")?e+"-movie":e+"-tv";a("body").append(v(q));z=setTimeout(function(){a("#uh-ajax-data").html("");a("#uh-title").text("");a("#uh-releaseDate").text("");a("#uh-channelname").text("");a("#uh-cc").removeClass("dv-badge");a("#uh-live").removeClass("dv-badge");a("#uh-starRating").html("");a("#uh-synopsis p").html("");a("#uh-grayBar").html("");a("#uh-greenBar").html("");a("#uh-orangeBar").html("");a("#uh-parentalControls").html("");
a("#uh-purchaseOptions").html("");a("#uh-watchListButton").html("");a("#uh-watchBox").html("");a("#uh-nextUp").html("");m=setTimeout(function(){"function"===typeof A&&"function"===typeof E&&(E("t0",e,new Date),A("bb",e,{wb:1}),x&&k.console.log(e+": clickToBodyBegin"));h(q,d,e,q);g(e,"render")},q.attr("data-render-hover"));a("#universal-hover").removeClass().addClass(q.data("type"));a("#prime-messaging").removeClass("prime").addClass(q.data("prime"));u=a.ajax({dataType:"json",timeout:1E4,data:{json:1},
url:"/gp/video/beard"+r(q),success:function(c){a("#uh-ajax-data").html(c);a("#uh-title").text(c.title);a("#uh-title").attr("href","/gp/product/"+c.asin+"/ref\x3ddv_web_wtls_ovl_tit");a("#uh-releaseDate").text(c.releaseDate);a("#uh-channelName").text(c.channelname);a("#uh-rating").text(c&&c.textRating?c.textRating:c.rating);a("#uh-rating").addClass("dv-"+c.rating);a("#uh-cc").addClass(null!==c.cc?"dv-badge":"");a("#uh-cc").text(c.cc);a("#uh-live").addClass(1===c.live?"dv-badge":"");a("#uh-live").text(1===
c.live?"Live":"");a("#uh-starRating").html(c.starRating);a("#uh-synopsis p").html(c.synopsis);a("#uh-grayBar").html(c.grayBar);a("#uh-greenBar").html(c.greenBar);a("#uh-orangeBar").html(c.orangeBar);a("#uh-parentalControls").html(c.parentalControls);a("#uh-purchaseOptions").html(c.purchaseOptions);a("#uh-watchListButton").html(c.watchListButton);a("#uh-watchBox").html(c.watchBox);a("#uh-nextUp").html(c.nextUp);a(".spinner").remove();g(e,"ajax");1===c.live&&b(q,c);h(q,d,e,q)},error:function(){f()}})},
q.attr("data-ajax-request"))}function b(b,t){var g=b.find(".dv-tile-image"),h=b.find(".dv-core-title"),k=b.find(".a-link-normal"),m=b.find(".dv-playback-text"),r=b.closest(".dv-carousel");h.html("");var u=b.data("asin");void 0===t.asin||null===t.asin||""===t.asin||void 0===t.siblingASINs||null===t.siblingASINs||t.siblingASINs.constructor!==Array||void 0!==u&&null!==u&&""!==u&&-1!==a.inArray(u,t.siblingASINs)?void 0!==t.asin&&null!==t.asin&&""!==t.asin||void 0===u||null===u||""===u?void 0!==b.data("asin")&&
null!==b.data("asin")&&""!==b.data("asin")||f():n.when("live-channel-framework").execute(function(a){var c=b.data("lcid");if(void 0!==c&&null!==c){var f=a.getChannelData(c);f&&d(m,function(){g.fadeOut(1E3,function(){l(b,r,g,f.source,f.dynamic_images);e(k,"asin");e(b,"asin");e(b,"type");g.fadeIn(1E3,function(){void 0!==m&&m.fadeIn(100);r.trigger("resize.carousel");h.html(f.title)})})})}}):d(m,function(){g.fadeOut(1E3,function(){void 0!==t.image&&null!==t.image&&""!==t.image?l(b,r,g,t.image,t.dynamic_images,
"dv-"+("tv"===t.contentType?"episode":"movie")):n.when("live-channel-framework").execute(function(a){var c=b.data("lcid");void 0!==c&&null!==c&&(a=a.getChannelData(c))&&l(b,r,g,a.source,a.dynamic_images)});c(k,"asin",t.asin);c(b,"asin",t.asin);c(b,"type","downloadable_"+t.contentType);g.fadeIn(1E3,function(){void 0!==m&&m.fadeIn(100);r.trigger("resize.carousel");h.html(t.title);C===b&&p(b)})})})}function l(a,b,d,e,f,g){n.when("dv-lazy-load").execute(function(a){a.loadImages(b)});d.attr("src",e);c(d,
"a-dynamic-image",JSON.stringify(f));a.removeClass("dv-movie dv-season dv-episode");void 0!==g&&a.addClass(g)}function d(a,b){f();void 0!==a&&null!==a&&0<a.length?a.fadeOut(100,b):b()}function c(a,b,c){a.data(b,c);a.attr("data-"+b,c)}function e(a,b){a.removeData(b);a.removeAttr("data-"+b)}function g(a,b){"render"===b&&"function"===typeof A?A("af",a,{wb:1}):"ajax"===b&&"function"===typeof A&&A("cf",a,{wb:1});w.push(b);x&&k.console.log(a+" event: "+b);2===w.length&&(x&&k.console.log(a+" eventMonitor has received two events: "+
w),"render"===w[0]&&(G.count(a+":spinner",1),x&&k.console.log(a+": box rendered before data available, updating spinner count")),"function"===typeof F&&(F("ld",a,{wb:1}),x&&k.console.log(a+": metrics submitted to server")))}function v(a){a.hasClass("video_rental");var b=void 0!==a.data("lcid")?'\x3cp id\x3d"uh-title"\x3e\x3c/p\x3e':'\x3ca href\x3d"#" id\x3d"uh-title"\x3e\x3c/a\x3e';a=void 0!==a.data("channelname")?'\x3cdiv id\x3d"uh-channelName" class\x3d"light-header"\x3e'+a.data("channelname")+
"\x3c/div\x3e":"";return'\x3cdiv id\x3d"universal-hover" class\x3d""\x3e\x3cspan id\x3d"arrow-hover"\x3e\x3cspan id\x3d"arrow"\x3e\x3c/span\x3e\x3c/span\x3e\x3cdiv id\x3d"header" class\x3d"a-spacing-small"\x3e\x3ch1 class\x3d"inline-header a-size-medium"\x3e'+b+'\x3c/h1\x3e\x3ch2 id\x3d"uh-releaseDate" class\x3d"light-header inline-header a-size-base a-spacing-small"\x3e\x3c/h2\x3e'+a+'\x3cp id\x3d"uh-starRating" class\x3d"a-size-mini a-spacing-mini rating"\x3e\x3c/p\x3e\x3cp class\x3d"a-size-mini a-text-center aiv-messaging" id\x3d"prime-messaging"\x3e\x3c/p\x3e\x3c/div\x3e\x3cspan class\x3d"spinner"\x3e\x3c/span\x3e\x3cdiv id\x3d"uh-grayBar" class\x3d"a-spacing-small"\x3e\x3c/div\x3e\x3cdiv id\x3d"uh-greenBar" class\x3d"a-spacing-small"\x3e\x3c/div\x3e\x3cdiv id\x3d"uh-orangeBar" class\x3d"a-spacing-small"\x3e\x3c/div\x3e\x3cdiv id\x3d"uh-purchaseOptions" class\x3d"a-spacing-small"\x3e\x3c/div\x3e\x3cdiv id\x3d"uh-synopsis"\x3e\x3cp class\x3d"a-size-mini a-spacing-small"\x3e\x3c/p\x3e\x3c/div\x3e\x3cspan id\x3d"uh-live" class\x3d"a-spacing-mini"\x3e\x3c/span\x3e\x3cspan id\x3d"uh-cc" class\x3d"a-spacing-mini"\x3e\x3c/span\x3e\x3cspan id\x3d"uh-rating" class\x3d"dv-badge a-spacing-mini"\x3e\x3c/span\x3e\x3cdiv id\x3d"uh-parentalControls" class\x3d"a-spacing-small"\x3e\x3c/div\x3e\x3cdiv id\x3d"uh-watchBox" class\x3d"a-spacing-small"\x3e\x3c/div\x3e\x3cdiv id\x3d"uh-watchListButton" class\x3d"a-spacing-small"\x3e\x3c/div\x3e\x3cdiv id\x3d"uh-nextUp" class\x3d"a-spacing-small"\x3e\x3c/div\x3e\x3c/div\x3e'}
function f(){u&&(u.abort(),u=null);a("#universal-hover").remove();a("#universal-hover").stop(!0,!0).hide()}function r(b){var c=b.parents(".shelf"),d="?";b={ASIN:b.attr("data-asin"),LCID:b.attr("data-lcid"),contextLinkText:c.attr("data-context-link-text")||b.attr("data-context-link-text"),contextLinkURL:c.attr("data-context-link-url")||b.attr("data-context-link-url"),shelfType:c.attr("data-shelf-type"),reftagPrefix:c.attr("data-reftag-prefix"),whyReasons:b.attr("data-why-reasons"),isByPostRental:b.hasClass("video_rental"),
relatedRequestId:a("#pageData").attr("data-request")};b.LCID="undefined"!==b.LCID&&b.LCID?b.LCID:"";b.contextLinkText="undefined"!==b.contextLinkText&&b.contextLinkText?b.contextLinkText:"";b.contextLinkURL="undefined"!==b.contextLinkURL&&b.contextLinkURL?b.contextLinkURL:"";b.shelfType="undefined"!==b.shelfType&&b.shelfType?b.shelfType:"";b.whyReasons="undefined"!==b.whyReasons&&b.whyReasons?b.whyReasons:"";b.reftagPrefix="undefined"!==b.reftagPrefix&&b.reftagPrefix?b.reftagPrefix:"";b.isByPostRental=
"undefined"!==b.isByPostRental&&b.isByPostRental?1:"";b.relatedRequestId="undefined"!==b.relatedRequestId&&b.relatedRequestId?b.relatedRequestId:"";return d+=a.param(b)}var z,m,u,w=[],C,A=k.uet,E=k.ues,F=k.uex,G=k.ue,x=0;if(0<a("#pageData").length)for(var B=a("#pageData").data("debug"),B=B.split(","),D=0;D<B.length;D++)x="verbose"===B[D]?1:x;a.fn.live&&(a(".dv-universal-hover-enabled").live("mouseenter",function(){w=[];if(!a("#universal-hover").length){var b=a(this);b.closest(".dv-standard-carousel").hasClass("dv-list-remove-item-highlight-selected")||
(C=b,p(b))}}),a(".dv-universal-hover-enabled").live("mouseleave click",function(b){C=void 0;clearTimeout(m);w=[];a(b.relatedTarget).is("#universal-hover, #arrow-hover, #arrow")||f()}),a("#universal-hover").live("mouseleave",function(b){w=[];0>a(b.relatedTarget).parents().index(a(this).data("ps"))&&f()}),a("a.remove-link, a.item-remove").live("click",function(b){b.preventDefault();var c=a(this).attr("data-asin"),d=a(this).attr("data-shelf-type");a.ajax({data:{asin:a(this).attr("data-asin"),token:a(this).attr("data-token"),
type:a(this).attr("data-shelf-type")},dataType:"json",success:function(b){if(b.success){a(this).unbind("click");var e=a("\x3cdiv/\x3e");b=a("\x3cp\x3e"+b.success+"\x3c/p\x3e");var f='ul.shelf[data-shelf-type\x3d"'+d+'"] '+('[data-asin\x3d"'+c+'"]');0<a(f).children(".confirmation-overlay").length||(e.addClass("confirmation-overlay").html(b).width(a(f).outerWidth()).height(a(f).outerHeight()),a(f).append(e).removeClass("dv-universal-hover-enabled").unbind("mouseenter"),e.hide().fadeIn())}},timeout:1E4,
url:"/gp/video/utilities/lists/ajax/hide.html"})}),a(".watch-tab-remove").live("click",function(){0===a("a.dv-cl-item-remove").length&&0<a("a.item-remove").length&&a("#universal-hover").find("a.item-remove").trigger("click")}),a(".watch-tab-add").live("click",function(){var b=a("#universal-hover").find("a.item-remove"),c=b.attr("data-asin"),b=b.attr("data-shelf-type");a('ul.shelf[data-shelf-type\x3d"'+b+'"] li[data-asin\x3d"'+c+'"]').children(".confirmation-overlay").fadeOut().remove()}),a("a.why-recommend-link").live("click",
function(b){b.preventDefault();b=a(this).attr("href");var c=k.innerHeight,d=Math.round(k.innerWidth/2-275),c=Math.round(.3*c);k.open(b,"whyRecommended","height\x3d450,width\x3d550,left\x3d"+d+",top\x3d"+c+",menubar\x3d0,scrollbars\x3d1,toolbar\x3d0,status\x3d0")}))})});
/* ******** */
(function(f){var d=window.AmazonUIPageJS||window.P,e=d._namespace||d.attributeErrors,b=e?e("DigitalVideoWebGiftCardAssets"):d;b.guardFatal?b.guardFatal(f)(b,window):b.execute(function(){f(b,window)})})(function(f,d,e){f.when("A","dv-async","aiv-alerts","aiv-modal").register("dv-gift-card",function(b,d,e){var c=b.$,g=d.create("dv-gift-card",f).ajax;({states:{RUNNING:2,READY:1},currentState:null,init:function(){this.id="dv-gift-card";this.addEventListeners();this.currentState=this.states.READY},addEventListeners:function(){var a=
this;c("body").delegate("#gc-giftcard","submit",function(c){c.preventDefault();a.submit()});b.on("dv:modal:click:submit:"+a.id,function(){a.submit()})},submit:function(){var a=this,b,d,e={retJSON:!0};a.currentState!==a.states.RUNNING&&(a.currentState=a.states.RUNNING,b=c("#gc-giftcard"),d=b.attr("action"),e.code=b.find(".dv-gc-input").val(),g(d,{params:e,success:function(b){var c=b.message;b.success?(a.updateGCBalances(b),a.updateModalSuccess(c)):a.updateModalFailure(c);a.currentState=a.states.READY},
error:function(b){a.updateModalFailure(b);a.currentState=a.states.READY}}))},updateModalFailure:function(a){this.showMessage(c(e.error(a,"block","light")))},updateModalSuccess:function(a){this.showMessage(c(e.success(a,"block","light")))},showMessage:function(a){c("#dv-gc-message-wrapper")[0]||this.addMessageWrapper();c("#dv-gc-message-wrapper").html(a)},addMessageWrapper:function(){c("\x3cdiv/\x3e").attr({id:"dv-gc-message-wrapper"}).insertAfter(c("#dv-gc-widget-heading"))},updateGCBalances:function(a){for(var b in a.balances)a.balances.hasOwnProperty(b)&&
c("#dv_gc_balances_"+b).html(a.balances[b])}}).init()})});
/* ******** */
(function(c){var d=window.AmazonUIPageJS||window.P,e=d._namespace||d.attributeErrors,a=e?e("DigitalVideoWebSeasonSelectorAssets"):d;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,d,e){c.when("A","a-dropdown").execute("dv-season-selector",function(a,c){var d=a.$,e=d(".dv-season-selector-drop-down .a-dropdown-prompt"),b=c.getSelect("dv-season-selector"),f=d(".dv-season-selector-drop-down"),g=f?f.data("redirect-link"):"";b&&b.options&&b.options.$select&&e&&(b=
b.options.$select,b=b.find(":selected").data("a-html-content"),e.html(b));a.on("a:dropdown:dv-season-selector:select",function(a){var b=a.value.split(":"),c=b[0],b=b[1];a=d(a.auiItemNode).html();e.html(a);document.location.href=g+c+"?ref_\x3d"+b})})});
/* ******** */
(function(e){var g=window.AmazonUIPageJS||window.P,r=g._namespace||g.attributeErrors,b=r?r("DigitalVideoWebDetailsAssets"):g;b.guardFatal?b.guardFatal(e)(b,window):b.execute(function(){e(b,window)})})(function(e,g,r){e.when("A","logging","aiv-modal","dv-async").register("watchlist-toggle",function(b,c,a,d){function l(a,d){function c(h){var f=h&&"added"===h.status?!0:!1;k.log("recieved wl response",h);1===h.success?b=p(d,f):"csrf_token_was_not_valid"===h.reason?n("dv-modal-session-expired"):m();h=
b("initial");a.val(h);a.attr({disabled:!1}).data({onWatchlist:f})}var b=p(d);return{callWatchlist:function(){var n={method:"POST",success:c,error:m,params:{ASIN:d.titleId,csrfToken:d.csrfToken,action:b("action"),pageType:d.pageType,subPageType:d.subPageType,dataType:"json"}},h=b("url");a.attr({disabled:!0});var f=b("process");a.val(f);k.log("wl called",h,n);q.ajax(h,n)}}}function p(a,d){d="undefined"!==typeof d?d:a.onWatchlist;return function(b){var n=d?"remove":"add";b=b.charAt(0).toUpperCase()+
b.slice(1);return a[n+b]}}function n(d){a.create({id:d}).show().on("dv:dv-modal:submit",h)}function h(){document.location.reload(!0)}function m(){n("dv-modal-generic-error")}var f=b.$,k=c.create("watchlist-toggle",e),q=d.create("watchlist-call-handler",e);k.log("bound events to",".dv-action-watchlist input:submit");f("body").delegate(".dv-action-watchlist input:submit","click",function(d){d.preventDefault();d=f(d.target);var a=d.data();k.log("initial data",a);a&&a.signInUrl&&""!==a.signInUrl?g.location.href=
a.signInUrl:d.attr("disabled")||l(d,a).callWatchlist()})});e.when("A","jQuery","logging","ready").register("dv-extender",function(b,c,a){var d=a.create("dv-extender",e),l={useEllipsis:!1,resizeDelay:400,hasToggle:!1,hasHiddenToggle:!1,speedQuick:200,maxSpeed:1E3},p=function(a,b){if("undefined"===typeof a)d.error("No element passed to Extender");else return this.elem=a,this.$elem=c(a),this.options=c.extend({},l,b,this.$elem.data("extender")),this};p.prototype={init:function(){"undefined"!==typeof this.$elem&&
(this.$content=this.$elem.find("p"),this.lineHeight=parseInt(this.$content.css("lineHeight"),10),this.originalHeight=this.$elem.height(),this.contentHeight=this.$content.height(),this.seeMoreText=this.options.strings?c("\x3cdiv/\x3e").html(this.options.strings.seeMore).text():"",this.seeLessText=this.options.strings?c("\x3cdiv/\x3e").html(this.options.strings.seeLess).text():"",this.maxOverflowLines="undefined"===typeof this.options.maxOverflowLines?1:this.options.maxOverflowLines,this.isOpen=this.startsOpen=
this.$elem.hasClass("dv-extender-open"),this.speed=this.options.speedQuick+this.contentHeight,this.speed=this.speed>this.options.maxSpeed?this.options.maxSpeed:this.speed,this.ellipsisOnCss={whiteSpace:"nowrap",textOverflow:"ellipsis",overflow:"hidden"},this.ellipsisOffCss={whiteSpace:"normal"},d.info(this),this.extend(),this.attachEvents())},extend:function(){var a=this.ellipsisOffCss,b=this.$elem.height();this.setContentHeight();this.$elem.css({height:b,"max-height":"none"});b=this.contentHeight<=
this.originalHeight+this.maxOverflowLines*this.lineHeight;d.debug("isContentFit",b);b?(this.expandToContentHeight(),this.hideLink()):(this.resetToggle(),this.startsOpen?this.expandToContentHeight():(this.resetOriginalHeight(),this.options.useEllipsis&&(a=this.ellipsisOnCss)),this.showLink());this.$elem.find("p").css(a)},expandToContentHeight:function(){var a=this;d.debug(a.contentHeight);a.$elem.stop().animate({height:a.contentHeight},a.speed,function(){a.$elem.css({height:"auto"})})},attachEvents:function(){var a=
this,b=c("html").hasClass("a-lt-ie9"),m=c(g),f=m.width(),k=!0,e,l;d.debug("isWindowResizeFiredOnElementChange",b);m.resize(function(){b&&(l=m.width(),k=!1,f!==l&&(k=!0,f=l));d.debug("isActualWindowResize",k);clearTimeout(e);e=setTimeout(function(){k&&a.extend()},a.resizeDelay)})},attachClickEvent:function(){var a=this;d.debug(this);a.$extenderAdjustLink&&a.$extenderAdjustLink.click(function(d){d.preventDefault();a.extenderToggle()})},showLink:function(){d.debug("hasToggle",this.options.hasToggle);
this.options.hasToggle?this.$elem.next(".dv-extender-link").show():this.createLink()},createLink:function(){this.$extenderAdjustLink=c("\x3ca\x3e\x3c/a\x3e");this.$extenderAdjustLink.addClass("dv-extender-link "+this.getDefaultLinkClass()).text(this.getDefaultLinkText()).attr("href","#").css({display:"none"}).insertAfter(this.$elem).slideDown(this.options.speedQuick);this.attachClickEvent();this.options.hasToggle=!0},getDefaultLinkClass:function(){d.debug("startsOpen",this.startsOpen);return this.startsOpen?
"dv-extender-see-less":"dv-extender-see-more"},getDefaultLinkText:function(){d.debug("startsOpen",this.startsOpen);return this.startsOpen?this.seeLessText:this.seeMoreText},hideLink:function(){d.debug(this);this.options.hasToggle&&(this.options.hasHiddenToggle=!0,this.resetToggle(),this.$elem.next(".dv-extender-link").hide())},resetOriginalHeight:function(){d.debug(this.originalHeight);this.$elem.stop().animate({height:this.originalHeight},this.speed)},resetToggle:function(){this.changeLink(this.getDefaultLinkText(),
this.getDefaultLinkClass())},setContentHeight:function(){this.$content.css(this.ellipsisOffCss);this.contentHeight=this.$content.height()},extenderToggle:function(){var a=0,b="",c=this.ellipsisOffCss,f=this.seeLessText,k="dv-extender-see-less";this.setContentHeight();this.isOpen=this.$elem.hasClass("dv-extender-open");d.debug(this.isOpen);this.isOpen?(a=this.originalHeight,b="",f=this.seeMoreText,k="dv-extender-see-more",this.options.useEllipsis&&(c=this.ellipsisOnCss)):(a=this.contentHeight,b="dv-extender-open");
this.changeLink(f,k);this.resizeContainer(a,b);this.$elem.find("p").css(c)},resizeContainer:function(a,b){var c=this;d.debug(a,b);c.$elem.removeClass("dv-extender-open").addClass(b).stop().animate({height:a},c.speed,function(){c.isOpen||(c.isOpen=!0,c.$elem.css({height:"auto"}))})},changeLink:function(a,b){var c=this.$elem.next(".dv-extender-link");d.debug(a,b);c.text(a).removeClass("dv-extender-see-more dv-extender-see-less").addClass(b)}};c(".dv-extender").each(function(){(new p(this)).init()});
return p});e.when("A").register("dv-image-loader",function(b){var c=b.$;return function(){var a=new Image;return{loadImageThenExecute:function(b,l){a.src=b;c(a).one("load",l).each(function(){this.complete&&c(this).load()})}}}()});e.when("A","dv-image-loader","ready").register("dv-heroshot",function(b,c){var a=b.$;return function(b,l,e){if(!b)return!1;"undefined"===typeof e&&(e=!0);var g=["aivDetailsBackgroundPanel"];e&&g.push("js-hide-on-play");a("\x3cdiv/\x3e").addClass(g.join(" ")).html("\x3cdiv class\x3d'heroImage'\x3e\x3cdiv class\x3d'aivDetailsGradient'\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e").prependTo(l).each(function(){c.loadImageThenExecute(b,
function(){a(".heroImage").css({display:"none"}).append(a("\x3cimg/\x3e").attr({src:b})).fadeIn(1E3)})})}});e.when("A","dv-heroshot","ready").execute(function(b,c){var a=b.$;(a=a(".dv-heroshot-widget").data("heroshot"))&&c(a,".dp-main")});e.when("jQuery","ready").execute(function(b){b(".dv-load-url-js-win").click(function(c){c.preventDefault();c=parseInt(b(this).data("jsWinHeight"),10)||660;var a=parseInt(b(this).data("jsWinWidth"),10)||680,d=g.screen.width/2-a/2,e=g.screen.height/2-c/2-70;0>d&&(d=
0);0>e&&(e=0);g.open(this.href,"_blank","location\x3dyes,left\x3d"+d+",top\x3d"+e+",width\x3d"+a+",height\x3d"+c)})});"use strict";e.when("A","jQuery","dv-ux","dv-ajax-reload","dv-player-integration","dv-web-player-cfg").register("dp-refresh-handlers",function(b,c,a,d,e,g){function n(){var a=c("#dv-buybox-play a:first").data();null!==a&&"object"===typeof a&&e.prepare({asin:a.asin,trailer:!1,position:a.resumeTime,ref:a.ref,videoType:a.videoType})}function h(a,b,c){return d.getWidgets({asin:a,loggingName:"dvweb-update-playback",
widgets:b,DOMRootID:c})}function m(a){a=a.asin;var b=c("#dv-episode-list").find('[data-aliases*\x3d"'+a+'"]').attr("id");b&&h(a,["js-ajaxable-episode-status"],b)}function f(){a.removeSpinner(c("#dv-action-box-wrapper"))}e.on("closed",function(b){if(b&&!b.trailer){var d=g.get("pageTitleID");d&&(h(d,["dv-action-box"],"dv-action-box-wrapper").then(f).then(n),a.addSpinner(c("#dv-action-box-wrapper")));m(b)}});e.on("asinChanged",m)});"use strict";e.when("A","dv-utils","jQuery").register("dv-trailer-view",
function(b,c,a){function d(){a(f.contentArea).height(l(p().height));a(f.webPlayer).css(p())}function l(b){var d=a(f.actionBox).outerHeight(!0);return Math.max(d,b)+a(f.titleContent).outerHeight(!0)+20}function p(){var b=a(f.actionBox).outerWidth()+20,b=a(f.titleContent).innerWidth()-b;return{width:b,top:a(f.titleContent).outerHeight(!0),left:20,height:Math.min(Math.floor(b/16*9)-20,600)}}function n(){g.navbar&&"function"===typeof g.navbar.lockFlyouts&&g.navbar.lockFlyouts()}function h(){g.navbar&&
"function"===typeof g.navbar.unlockFlyouts&&g.navbar.unlockFlyouts()}function m(a){e.when("navbarJSLoaded").execute(a)}var f={actionBox:"#dv-action-box-wrapper",titleContent:"#dv-dp-title-content",webPlayer:"#dv-web-player",hideDuringPlay:".js-hide-on-play-left",contentArea:".dv-dp-content"},k=c.makeClosure(!1),q;return{open:function(c){m(n);k(!0);q=a(f.contentArea).outerHeight(!0);a(f.hideDuringPlay).animate({opacity:0},c||600,function(){a(f.webPlayer).addClass("trailer-player")});a(f.contentArea).addClass("trailer-view").height(q);
d();b.on.resize(d)},close:function(c){m(h);k(!1);a(f.webPlayer).removeClass("trailer-player").removeAttr("style");a(f.contentArea).height(q);a(f.hideDuringPlay).animate({opacity:1},c||600,function(){a(f.contentArea).removeClass("trailer-view").removeAttr("style")});b.off("resize",d)},calculateContainerHeight:l,getPlayerPosition:p,isPlaying:k.getAccessor()}});e.when("dv-player-integration","dv-player-default-view","dv-trailer-view").execute(function(b,c,a){b.on("play",function(b){e.when("dv-ready-atf").execute(function(){a.isPlaying()&&
a.close();b.trailer?a.open():c.open()})});b.on("closed",function(b){b.trailer?a.close():c.close()})});"use strict";e.when("dv-web-player-cfg","dv-live-incompatable","aiv-modal").register("dv-live-notification",function(b,c,a){c(function(){var d=b.get("strings").liveUnsupportedModal,c=a.create({id:"dv-live-unsupported",content:d.body,header:{text:d.header},buttons:[{type:"submit",text:d.confirm,customEvent:"closeLiveModal"}]});c.on("closeLiveModal",function(){c.remove()});c.show()})});"use strict";
e.when("dv-closure").register("dv-utils",function(b){return{makeClosure:b}});"use strict";e.register("dv-closure",function(){return function(b){function c(b){if("undefined"===typeof b)return a;a=b}var a=b;c.getAccessor=function(){return function(){return a}};return c}});"use strict";e.when("deeplinking","watchlist-toggle","dv-web-player-cfg","purchase-video").execute(function(){"function"===typeof g.setCSMReq&&g.setCSMReq("cf");if("function"===typeof g.uet){g.uet("cf");var b="complete"===document.readyState;
"object"===typeof g.ue&&"function"===typeof g.ue.tag&&g.ue.tag(b?"cf-after-load":"cf-before-load");b&&"function"===typeof g.uex&&g.uex("ld")}});e.when("dv-web-player-csm").execute(function(b){b("dv-detail")})});
/* ******** */
