(function(a,d,w){function l(a){for(var b={},c,d,e=0;e<a.length;e++)d=a[e],c=d.r+d.s+d.m,d.c&&(b[c]||(b[c]=[]),b[c].push(a[e]));return b}function k(a){for(var b=1;b<arguments.length;b++){var c=arguments[b];try{if(c.isSupported)return c.send(a)}catch(d){}}}function u(){for(var a=0;a<e.length;a++)e[a]();m.length&&k(l(m.splice(0,m.length)),M,L,G);F=I=0}function A(b,c,f){f=f||{};0===f.bf&&n.isBF||(b={r:f.r||n.rid,s:f.s||a.ue_sid,m:f.m||a.ue_mid,mkt:f.mkt||a.ue_mkt,sn:f.sn||a.ue_sn,c:c,d:b,t:f.t||n.d(),
cs:f.c&&a.ue_qsl},f.b?k(l([b]),M,G):f.nb?k(l([b]),M,L,G):f.img||K[c]?k(l([b]),G):f.ff?(m.push(b),u()):f.n?(m.push(b),0===N?u():F||(F=d.setTimeout(u,N))):(m.push(b),I||(I=d.setTimeout(u,J))))}function g(a,b,c){H++;H==h&&A({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},d.ue_err_chan||"jserr");(H<h||c&&c.il)&&A(a,b,c)}function v(){if(!D){for(var a=0;a<b.length;a++)b[a]();for(a=0;a<e.length;a++)e[a]();k(l(m.splice(0,m.length)),M,G);D=!0}}var x={};(function(){function a(b){return 10>
b?"0"+b:b}function b(a){d.lastIndex=0;return d.test(a)?'"'+a.replace(d,function(a){var b=g[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,d){var q,g,n,B,p=e,y,E=d[a];E&&"object"===typeof E&&"function"===typeof E.toJSON&&(E=E.toJSON(a));"function"===typeof h&&(E=h.call(d,a,E));switch(typeof E){case "string":return b(E);case "number":return isFinite(E)?String(E):"null";case "boolean":case "null":return String(E);case "object":if(!E)return"null";
e+=m;y=[];if("[object Array]"===Object.prototype.toString.apply(E)){B=E.length;for(q=0;q<B;q+=1)y[q]=c(q,E)||"null";n=0===y.length?"[]":e?"[\n"+e+y.join(",\n"+e)+"\n"+p+"]":"["+y.join(",")+"]";e=p;return n}if(h&&"object"===typeof h)for(B=h.length,q=0;q<B;q+=1)"string"===typeof h[q]&&(g=h[q],(n=c(g,E))&&y.push(b(g)+(e?": ":":")+n));else for(g in E)Object.prototype.hasOwnProperty.call(E,g)&&(n=c(g,E))&&y.push(b(g)+(e?": ":":")+n);n=0===y.length?"{}":e?"{\n"+e+y.join(",\n"+e)+"\n"+p+"}":"{"+y.join(",")+
"}";e=p;return n}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(b){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(a){return this.valueOf()});var d=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e,m,g={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},h;"function"!==typeof x.stringify&&(x.stringify=function(a,b,d){var q;m=e="";if("number"===typeof d)for(q=0;q<d;q+=1)m+=" ";else"string"===typeof d&&(m=d);if((h=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return c("",{"":a})})})();var r=function(){function a(b,c){if(null==b)return c.push("!n");if("number"===typeof b)return c.push("!"+b);if("string"===
typeof b)return"\\"==b[b.length-1]?c.push("'"+b.replace(/'/g,"\\'")+"u005C'"):c.push("'"+b.replace(/'/g,"\\'")+"'");if("boolean"===typeof b)return c.push(b?"!t":"!f");if(b instanceof Array){c.push("*");for(var d=0;d<b.length;d++)a(b[d],c);return c.push(")")}if("object"==typeof b){c.push("(");for(d in b)b.hasOwnProperty(d)&&(c.push(d),a(b[d],c));return c.push(")")}return c.push("!n")}return{stringify:function(b){var c=[];a(b,c);return c.join("")}}}(),p=a.ue_qsl||2E3,h=1E3,z=function(){},t=d.JSON&&
d.JSON.stringify||x&&x.stringify,C=r.stringify,n=a.ue||{},r=a.uet||z;(a.uet||z)("bb","ue_frst_v2",{wb:1});var c="//"+a.ue_furl+"/1/batch/1/OE/",m=[],b=[],e=[],D=!1,F,I,N=void 0===a.ue_hpfi?1E3:a.ue_hpfi,J=void 0===a.ue_lpfi?1E4:a.ue_lpfi,K={"scheduled-delivery":1},H=0,L=function(){function b(){if(d.XDomainRequest){var a=new XDomainRequest;a.onerror=z;a.ontimeout=z;a.onprogress=z;a.onload=z;a.timeout=0;return a}if(d.XMLHttpRequest){a=new XMLHttpRequest;if(!("withCredentials"in a))throw"";return a}if(d.ActiveXObject){for(var c=
0;c<f.length&&!a;c++)try{a=new ActiveXObject(f[c]),f=[f[c]]}catch(e){}return a}}function e(b){for(var c=[],f=b[0]||{},d=0;d<b.length;d++){var m={};m[b[d].c]=b[d].d;c.push(m)}return{rid:f.r||n.rid,sid:f.s||a.ue_sid,mid:f.m||a.ue_mid,mkt:f.mkt||a.ue_mkt,sn:f.sn||a.ue_sn,reqs:c}}var f="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");return{send:function(a){for(var f in a)if(a.hasOwnProperty(f)&&a[f].length){var d=e(a[f]),m=b();
if(!m)throw"";m.open("POST",c,!0);m.setRequestHeader&&m.setRequestHeader("Content-type","text/plain");m.send(t(d))}},buildPOSTBodyLog:e,isSupported:!0}}(),G=function(){return{send:function(b){for(var d in b)if(b.hasOwnProperty(d)){for(var f=b[d],e=f,m={},g=void 0,h=0;h<e.length;h++)g=e[h].c,m[g]||(m[g]=[]),m[g].push(e[h]);var f=f[0]||{},e=f.sn||a.ue_sn,f=c+(f.m||a.ue_mid)+":"+(f.s||a.ue_sid)+":"+(f.r||n.rid)+(e?":"+e:""),e=[],g=f,h=[],k=void 0;for(k in m)if(m.hasOwnProperty(k))for(var l=0;l<m[k].length;l++){var v=
m[k][l],r=encodeURIComponent((v.cs?C:t)(v.d));h.push({l:r,t:v.t,p:1,c:k,d:v.cs?"c":"j"})}m=h;h=void 0;k="$";for(v=0;v<m.length;){l=m[v];h!=l.c?(g+=k+l.c+"=",k="&",h=l.c):g+=",";var r=g,D=l.d+":",w=l,g=(w.l.match(".{1,"+(p-g.length)+"}[^%]{0,2}")||[])[0]||"";w.l=w.l.substr(g.length);g=r+(D+g+":"+l.t);if(l.l)g+=":"+l.p++ +"_",e.push(g),g=f,k="$",h=0;else if(v++,1!=l.p)for(g+=":"+l.p+"_"+l.p,r=0;r<l.p-1;r++)e[e.length-r-1]+=l.p}e.push(g);f=e;for(e=0;e<f.length;e++)(new Image).src=f[e]}},isSupported:!0}}(),
M=function(){return{send:function(a){for(var b in a)if(a.hasOwnProperty(b)){var f=L.buildPOSTBodyLog(a[b]);if(!navigator.sendBeacon(c,t(f)))throw"";}},isSupported:!!navigator.sendBeacon}}();n._fic=G;n._fac=L;n._fbc=M;n._flq=m;n.sid=n.sid||a.ue_sid;n.mid=n.mid||a.ue_mid;n.furl=n.furl||a.ue_furl;n.sn=n.sn||a.ue_sn;n.isBF=function(){var a=d.performance||d.webkitPerformance,b=w.ue_backdetect&&w.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,c=n.bfini;return a&&a.navigation&&2===a.navigation.type||
1<c||!c&&1<b}();try{d.amznJQ&&d.amznJQ.declareAvailable&&d.amznJQ.declareAvailable("forester-client"),d.P&&d.P.register&&d.P.register("forester-client",z)}catch(O){a.ueLogError(O,{logLevel:"WARN"})}(function(){n.log&&n.log.isStub&&(n.log.replay(function(a,b,c){var d=a[2]||{};d.t=b;d.r=c;d.n=1;g(a[0],a[1],d)}),n.onunload.replay(function(a){b.push(a[0])}),n.onflush.replay(function(a){e.push(a[0])}))})();n.log=g;n.log.reset=function(){H=0};n.onunload=function(a){b.push(a)};n.onflush=function(a){e.push(a)};
n.attach("beforeunload",v);n.attach("pagehide",v);r("ld","ue_frst_v2",{wb:1})})(ue_csm,window,document);
(function(a,d){function w(a){if(a)return a.replace(/^\s+|\s+$/g,"")}function l(c,d){if(!c)return{};var b="INFO"===d.logLevel;c.m&&c.m.message&&(c=c.m);var e=d.m||d.message||"",e=c.m&&c.m.message?e+c.m.message:c.m&&c.m.target&&c.m.target.tagName?e+("Error handler invoked by "+c.m.target.tagName+" tag"):c.m?e+c.m:c.message?e+c.message:e+"Unknown error",e={m:e,name:c.name,type:c.type,csm:h+" "+(c.fromOnError?"onerror":"ueLogError")},g,p,l=0,r;e.logLevel=d.logLevel||v;d.adb&&(e.adb=d.adb);if(g=d.attribution)e.attribution=
""+g;if(!b){e.pageURL=d.pageURL||""+(window.location?window.location.href:"")||"missing";e.f=c.f||c.sourceURL||c.fileName||c.filename||c.m&&c.m.target&&c.m.target.src;e.l=c.l||c.line||c.lineno||c.lineNumber;e.c=c.c?""+c.c:c.c;e.s=[];e.t=a.ue.d();if((b=c.stack||(c.err?c.err.stack:""))&&b.split)for(e.csm+=" stack",g=b.split("\n");l<g.length&&e.s.length<z;)(b=g[l++])&&e.s.push(w(b));else for(e.csm+=" callee",p=k(c.args||arguments,"callee"),g=l=0;p&&l<z;)r=t,p.skipTrace||(b=p.toString())&&b.substr&&(r=
0===g?4*t:r,r=1==g?2*t:r,e.s.push(b.substr(0,r)),g++),p=k(p,"caller"),l++;if(!e.f&&0<e.s.length&&(l=e)&&l.s){var u,b=0<l.s.length?l.s[0]:"";g=1<l.s.length?l.s[1]:"";b&&(u=b.match(n));u&&3==u.length||!g||(u=g.match(C));u&&3==u.length&&(l.f=u[1],l.l=u[2])}}return e}function k(a,d){try{return a[d]}catch(b){}}function u(c,m){if(c){var b=l(c,m);a.ue.log(b,m.channel||g,{nb:1});"function"===typeof ue_err.elh&&ue_err.elh(c,m);try{if(!c.fromOnError){var e=d.console,h=d.JSON,n="Error logged with the Track&Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";
if(e){if(h&&h.stringify)try{n+=h.stringify(b)}catch(p){n+="no info provided; converting to string failed"}else n+=b.m;"function"===typeof e.error?e.error(n,b):"function"===typeof e.log&&e.log(n,b)}}}catch(k){}}}function A(c,d){if(c&&!(a.ue_err.ec>a.ue_err.mxe)){a.ue_err.ter.push(c);d=d||{};var b=c.logLevel||d.logLevel;d.logLevel=b;d.attribution=c.attribution||d.attribution;b&&b!==v&&b!==x&&b!==r&&b!==p||a.ue_err.ec++;b&&b!=v||ue_err.ecf++;u(c,d)}}if(!a.ueLogError||a.ueLogError.isStub){var g=a.ue_err_chan||
"jserr",v="FATAL",x="ERROR",r="WARN",p="DOWNGRADED",h="v5",z=20,t=256,C=/\(?([^\s]*):(\d+):\d+\)?/,n=/.*@(.*):(\d*)/;u.skipTrace=1;l.skipTrace=1;A.skipTrace=1;(function(){if(a.ue_err.erl){var c=a.ue_err.erl.length,d,b;for(d=0;d<c;d++)b=a.ue_err.erl[d],u(b.ex,b.info);ue_err.erl=[]}})();a.ueLogError=A}})(ue_csm,window);
(function(a,d){a.ue_cel||(a.ue_cel=function(){function w(a,b){b?b.r=C:b={r:C,c:1};b.clog&&h.clog?h.clog(a,b.ns||x,b):b.glog&&h.glog?h.glog(a,b.ns||x,b):h.log(a,b.ns||x,b)}function l(){var a=g.length;if(0<a){for(var b=[],c=0;c<a;c++){var d=g[c].api;d.ready()?(d.on({ts:h.d,ns:x}),v.push(g[c]),w({k:"mso",n:g[c].name,t:h.d()})):b.push(g[c])}g=b}}function k(){if(!k.executed){for(var a=0;a<v.length;a++)v[a].api.off&&v[a].api.off({ts:h.d,ns:x});u();w({k:"eod",t0:h.t0,t:h.d()},{c:1,il:1});k.executed=1;for(a=
0;a<v.length;a++)g.push(v[a]);v=[];clearTimeout(r);clearTimeout(p)}}function u(){w({k:"hrt",t:h.d()},{c:1,il:1,n:1})}var A=void 0===typeof d.ue_cel_hrt?-1:d.ue_cel_hrt,g=[],v=[],x=a.ue_cel_ns||"cel",r,p,h=a.ue,z=a.uet,t=a.uex,C=h.rid,n=function(){var a=d.performance;return a&&a.navigation&&2===a.navigation.type}(),c=d.requestAnimationFrame||function(a){a()};if(n)w({k:"bft",t:h.d()});else return"function"==typeof z&&z("bb","csmCELLSframework",{wb:1}),setTimeout(l,0),h.onunload(k),r=setTimeout(k,6E5),
0<A&&(p=setInterval(u,A)),"function"==typeof t&&t("ld","csmCELLSframework",{wb:1}),{registerModule:function(a,b){g.push({name:a,api:b});w({k:"mrg",n:a,t:h.d()});l()},reset:function(a){w({k:"rst",t0:h.t0,t:h.d()});g=g.concat(v);v=[];for(var b=g.length,c=0;c<b;c++)g[c].api.off(),g[c].api.reset();C=a||h.rid;l();clearTimeout(r);r=setTimeout(k,6E5);k.executed=0},timeout:function(a,b){return d.setTimeout(function(){c(a)},b)},log:w}}())})(ue_csm,window);
(function(a,d,w){a.ue_pdm||!a.ue_cel||ue.isBF||(a.ue_pdm=function(){function l(){var b={w:g.width,aw:g.availWidth,h:g.height,ah:g.availHeight,cd:g.colorDepth,pd:g.pixelDepth},c={w:(w.body||{}).scrollWidth,h:(w.body||{}).scrollHeight};p&&p.w==b.w&&p.h==b.h&&p.aw==b.aw&&p.ah==b.ah&&p.pd==b.pd&&p.cd==b.cd||(p=b,p.t=x(),p.k="sci",C(p));h&&h.w==c.w&&h.h==c.h||(h=c,h.t=x(),h.k="doi",C(h));v=a.ue_cel.timeout(l,r)}function k(){!1!==z&&C({k:"ebl",t:x()},{ff:1});z=!1}function u(){!0!==z&&C({k:"efo",t:x()});
z=!0}function A(){d.setTimeout(function(){w[e]?k():u()},0)}var g,v,x,r,p,h,z=null,t=a.ue,C=a.ue_cel.log,n=a.uet,c=a.uex,m=1===d.ue_cel_viz&&t.pageViz,b=m&&t.pageViz.event,e=m&&t.pageViz.propHid;"function"==typeof n&&n("bb","csmCELLSpdm",{wb:1});return{on:function(e){r=e.timespan||500;x=e.ts;g=d.screen;t.attach&&(m&&t.attach(b,A,w),t.attach("blur",k,d),t.attach("focus",u,d));e=d.location;C({k:"pmd",o:e.origin,p:e.pathname,t:x()});a.ue_cel.timeout(l,0);"function"==typeof c&&c("ld","csmCELLSpdm",{wb:1})},
off:function(a){clearTimeout(v);t.detach&&(m&&t.detach(b,A,w),t.detach("blur",k,d),t.detach("focus",u,d));t.count&&(t.count("cel.PDM.TotalExecutions",0),t.count("cel.PDM.TotalExecutionTime",0),t.count("cel.PDM.AverageExecutionTime",0/0))},ready:function(){return w.body&&a.ue_cel&&a.ue_cel.log},reset:function(){p=h=null}}}(),a.ue_cel&&a.ue_cel.registerModule("page module",a.ue_pdm))})(ue_csm,window,document);
(function(a,d){a.ue_vpm||!a.ue_cel||ue.isBF||(a.ue_vpm=function(){function w(){var a=g(),c={w:d.innerWidth,h:d.innerHeight,x:d.pageXOffset,y:d.pageYOffset};k&&k.w==c.w&&k.h==c.h&&k.x==c.x&&k.y==c.y||(c.t=a,c.k="vpi",k=c,p(k,{clog:1}));u=0;v=g()-a;x+=1}function l(){u||(u=a.ue_cel.timeout(w,A))}var k,u,A,g,v=0,x=0,r=a.ue,p=a.ue_cel.log,h=a.uet,z=a.uex,t=r.attach,C=r.detach;"function"==typeof h&&h("bb","csmCELLSvpm",{wb:1});return{on:function(d){g=d.ts;A=d.timespan||100;a.ue_cel.timeout(w,0);t&&(t("scroll",
l),t("resize",l));"function"==typeof z&&z("ld","csmCELLSvpm",{wb:1})},off:function(a){clearTimeout(u);C&&(C("scroll",l),C("resize",l));r.count&&(r.count("cel.VPI.TotalExecutions",x),r.count("cel.VPI.TotalExecutionTime",v),r.count("cel.VPI.AverageExecutionTime",v/x))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){k=void 0},getVpi:function(){return k}}}(),a.ue_cel&&a.ue_cel.registerModule("viewport module",a.ue_vpm))})(ue_csm,window);
(function(a,d,w){if(!a.ue_fem&&a.ue_cel){var l=a.ue||{};!l.isBF&&!a.ue_fem&&w.querySelector&&d.getComputedStyle&&[].forEach&&(a.ue_fem=function(){function k(a,b){return a>b?3>a-b:3>b-a}function u(a,b){var c=d.pageXOffset,f=d.pageYOffset,e;a:{try{if(a){var q=a.getBoundingClientRect();e={x:q.left+c|0,y:q.top+f|0,w:q.width|0,h:q.height|0,d:(0===a.offsetWidth&&0===a.offsetHeight)|0}}else e=void 0;break a}catch(g){}e=void 0}if(e&&!a.cel_b)a.cel_b=e,m({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,
y:a.cel_b.y,t:b,k:"ewi",cl:a.className},{clog:1});else{if(c=e)c=a.cel_b,f=e,c=f.d===c.d&&1===f.d?!1:!(k(c.x,f.x)&&k(c.y,f.y)&&k(c.w,f.w)&&k(c.h,f.h)&&c.d===f.d);c&&(a.cel_b=e,m({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:b,k:"ewi"},{clog:1}))}}function A(a,b){var d;d=a.c?w.getElementsByClassName(a.c):a.id?[w.getElementById(a.id)]:w.querySelectorAll(a.s);a.w=[];for(widgetIndex=0;widgetIndex<d.length;widgetIndex++){var e=d[widgetIndex];e&&(e.cel_n||(e.cel_n=e.getAttribute("cel_widget_id")||
(a.id_gen||c)(e,widgetIndex)||e.id),a.w.push(e),x(f,e,b))}}function g(a,c){b.contains(a)||m({n:a.cel_n,t:c,k:"ewd"},{clog:1})}function v(a){G.length&&ue_cel.timeout(function(){for(var b=S(),c=!1;S()-b<t&&!c;){for(c=O;0<c--&&0<G.length;){var f=G.shift();q[f.type](f.elem,f.time)}c=0===G.length}M++;v(a)},0)}function x(a,b,c){G.push({type:a,elem:b,time:c})}function r(a,b){for(var c=0;c<n.length;c++)for(var f=n[c].w||[],d=0;d<f.length;d++)x(a,f[d],b)}function p(){L||(L=a.ue_cel.timeout(function(){L=null;
var a=C();r(y,a);for(var b=0;b<n.length;b++)x(Q,n[b],a);v(a)},z))}function h(){L||H||(H=a.ue_cel.timeout(function(){H=null;var a=C();r(f,a);v(a)},z))}var z=50,t=4.5,C,n=[],c=function(){},m=a.ue_cel.log,b,e,D,F,I=d.MutationObserver||d.WebKitMutationObserver||d.MozMutationObserver,N=!!I,J,K,H,L,G=[],M=0,O=null,y="removedWidget",Q="updateWidgets",f="processWidget",q,R=d.performance||{},S=R.now&&function(){return R.now()}||function(){return Date.now()};"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});
return{on:function(c){function f(){if(D&&F&&b&&b.contains&&b.getBoundingClientRect&&C){q={removedWidget:g,updateWidgets:A,processWidget:u};if(N){var a={attributes:!0,subtree:!0};J=new I(h);K=new I(p);J.observe(b,a);K.observe(b,{childList:!0,subtree:!0});K.observe(e,a)}else D.call(b,"DOMAttrModified",h),D.call(b,"DOMNodeInserted",p),D.call(b,"DOMNodeRemoved",p),D.call(e,"DOMNodeInserted",h),D.call(e,"DOMNodeRemoved",h);p()}}b=w.body;e=w.head;D=b.addEventListener;F=b.removeEventListener;C=c.ts;n=a.cel_widgets||
[];O=c.bs||5;l.deffered?f():l.attach&&l.attach("load",f);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){D&&F&&b&&b.contains&&b.getBoundingClientRect&&C&&(K&&(K.disconnect(),K=null),J&&(J.disconnect(),J=null),F.call(b,"DOMAttrModified",h),F.call(b,"DOMNodeInserted",p),F.call(b,"DOMNodeRemoved",p),F.call(e,"DOMNodeInserted",h),F.call(e,"DOMNodeRemoved",h));l.count&&l.count("cel.widgets.batchesProcessed",M)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){n=a.cel_widgets||
[]}}}(),a.ue_cel&&a.ue_fem&&a.ue_cel.registerModule("features module",a.ue_fem))}})(ue_csm,window,document);
(function(a,d){a.ue_mcm||!a.ue_cel||a.ue.isBF||(a.ue_mcm=function(){function w(a){try{if(a.id)return"//*[@id='"+a.id+"']";var d,g=1,p;for(p=a.previousSibling;p;p=p.previousSibling)p.nodeName==a.nodeName&&(g+=1);d=g;var h=a.nodeName;1!=d&&(h+="["+d+"]");a.parentNode&&(h=w(a.parentNode)+"/"+h);return h}catch(l){return"DETACHED"}}function l(a,l){var r=a.srcElement||a.target||{},p={k:k,w:(l||{}).ow||(d.body||{}).scrollWidth,h:(l||{}).oh||(d.body||{}).scrollHeight,t:(l||{}).ots||u(),x:a.pageX,y:a.pageY,
p:w(r),n:r.nodeName};a.button&&(p.b=a.button);r.href&&(p.r=r.href);r.id&&(p.i=r.id);r.className&&r.className.split&&(p.c=r.className.split(/\s+/));g(p,{c:1})}var k="mcm",u,A=a.ue,g=a.ue_cel.log;return{on:function(g){u=g.ts;a.ue_cel_stub&&a.ue_cel_stub.replayModule(k,l);A.attach&&A.attach("click",l,d)},off:function(a){A.detach&&A.detach("click",l,d)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){}}}(),a.ue_cel&&a.ue_cel.registerModule("mouse click module",a.ue_mcm))})(ue_csm,document);
(function(a,d){a.ue_mmm||!a.ue_cel||a.ue.isBF||(a.ue_mmm=function(w){function l(a,b){var c={x:a.pageX||a.x||0,y:a.pageY||a.y||0,t:x()};!b&&I&&(c.t-I.t<A||c.x==I.x&&c.y==I.y)||(I=c,e.push(c))}function k(){if(e.length){m=H.now();for(var a=0;a<e.length;a++){var d=e[a],l=a;N=e[F];J=d;var p=void 0;if(!(p=2>l)){a:if(e[l].t-e[l-1].t>u)p=0;else{for(p=F+1;p<l;p++){var k=N,r=J,f=e[p];K=(r.x-k.x)*(k.y-f.y)-(k.x-f.x)*(r.y-k.y);if(K*K/((r.x-k.x)*(r.x-k.x)+(r.y-k.y)*(r.y-k.y))>g){p=0;break a}}p=1}p=!p}p?F=l-1:
D.pop();D.push(d)}b=H.now()-m;t=Math.min(t,b);C=Math.max(C,b);n=(n*c+b)/(c+1);c+=1;h({k:v,e:D,min:Math.floor(1E3*t),max:Math.floor(1E3*C),avg:Math.floor(1E3*n)},{c:1});e=[];D=[];F=0}}var u=100,A=20,g=25,v="mmm1",x,r,p=a.ue,h=a.ue_cel.log,z,t=1E3,C=0,n=0,c=0,m,b,e=[],D=[],F=0,I,N,J,K,H=w&&w.now&&w||Date.now&&Date||{now:function(){return(new Date).getTime()}};return{on:function(a){x=a.ts;r=a.ns;p.attach&&p.attach("mousemove",l,d);z=setInterval(k,3E3)},off:function(a){r&&(I&&l(I,!0),k());clearInterval(z);
p.detach&&p.detach("mousemove",l,d)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){e=[];D=[];F=0;I=null}}}(window.performance),a.ue_cel&&a.ue_cel.registerModule("mouse move module",a.ue_mmm))})(ue_csm,document);
ue_csm.ue.exec(function(a,d){var w=function(){},l=function(){return{send:function(a,l){if(l&&a){var g;if(d.XDomainRequest)g=new XDomainRequest,g.onerror=w,g.ontimeout=w,g.onprogress=w,g.onload=w,g.timeout=0;else if(d.XMLHttpRequest){if(g=new XMLHttpRequest,!("withCredentials"in g))throw"";}else g=void 0;if(!g)throw"";g.open("POST",a,!0);g.setRequestHeader&&g.setRequestHeader("Content-type","text/plain");g.send(l)}},isSupported:!0}}(),k=function(){return{send:function(a,d){if(a&&d&&!navigator.sendBeacon(a,
d))throw"";},isSupported:!!navigator.sendBeacon}}();a.ue._ajx=l;a.ue._sBcn=k},"Transportation-clients")(ue_csm,window);
ue_csm.ue.exec(function(a,d){function w(){for(var a=0;a<arguments.length;a++){var f=arguments[a];try{var e;if(f.isSupported){var g=Q.buildPayload(D,b);e=f.send(c,g)}else throw dummyException;return e}catch(m){}}C({m:"All supported clients failed",attribution:"CSMSushiClient_TRANSPORTATION_FAIL",f:"sushi-client.js",logLevel:"ERROR"},d.ue_err_chan||"jserr")}function l(){if(b.length){for(var a=0;a<H.length;a++)H[a]();w(t._sBcn||{},t._ajx||{});b=[];e={};D={};G=M=F=I=0}}function k(){var a=new Date,b=function(a){return 10>
a?"0"+a:a};return Date.prototype.toISOString?a.toISOString():a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())+"."+String((a.getUTCMilliseconds()/1E3).toFixed(3)).slice(2,5)+"Z"}function u(a){try{return JSON.stringify(a)}catch(b){}return null}function A(c,f,e,g){var m=!1;g=g||{};J++;J==r&&C({m:"Max number of Sushi Logs exceeded",f:"sushi-client.js",logLevel:"ERROR",attribution:"CSMSushiClient_MAX_CALLS"},d.ue_err_chan||
"jserr");var n;if(n=!(J>=r))(n=c&&-1<c.constructor.toString().indexOf("Object")&&f&&-1<f.constructor.toString().indexOf("String")&&e&&-1<e.constructor.toString().indexOf("String"))||N++;n&&(c.producerId=c.producerId||f,c.schemaId=c.schemaId||e,c.timestamp=k(),f=Date.now?Date.now():+new Date,c.messageId=a.ue_id+"-"+f+"-"+J,g&&!g.ssd&&(c.sessionId=c.sessionId||a.ue_sid,c.requestId=c.requestId||a.ue_id,c.obfuscatedMarketplaceId=c.obfuscatedMarketplaceId||a.ue_mid),(f=u(c))?(f=f.length,(b.length==p||
F+f>h)&&l(),F+=f,c={data:Q.compressEvent(c)},b.push(c),(g||{}).n?0===O?l():G||(G=d.setTimeout(l,O)):M||(M=d.setTimeout(l,y)),m=!0):m=!1);!m&&a.ue_int&&console.error("Invalid JS Nexus API call");return m}function g(){if(!L){for(var a=0;a<K.length;a++)K[a]();for(a=0;a<H.length;a++)H[a]();b.length&&w(t._sBcn||{});L=!0}}function v(a){K.push(a)}function x(a){H.push(a)}var r=1E3,p=499,h=524288,z=function(){},t=a.ue||{},C=t.log||z,n=a.uex||z;(a.uet||z)("bb","ue_sushi_v1",{wb:1});var c=a.ue_surl||"https://unagi-na.amazon.com/1/events/com.amazon.csm.nexusclient.gamma",
m=["messageId","timestamp"],b=[],e={},D={},F=0,I=0,N=0,J=0,K=[],H=[],L=!1,G,M,O=void 0===a.ue_hpsi?1E3:a.ue_hpsi,y=void 0===a.ue_lpsi?1E4:a.ue_lpsi,Q=function(){function a(b){e[b]="#"+I++;D[e[b]]=b;return e[b]}function c(a){if(a)switch(typeof a){case "number":return!(isNaN(a)||Infinity===a)&&a.toString().length>("#"+I).length;case "boolean":break;case "string":return a.length>("#"+I).length;default:return!0}return!1}function f(b){if(c(b)){var d=0;b instanceof Array?d=2:b instanceof Function?d=0:b instanceof
Object&&(d=1);switch(d){case 0:b=e[b]?e[b]:a(b);break;case 2:var g=b;b=[];for(var d=g.length,h=0;h<d;h++)b[h]=f(g[h]);break;case 1:d={};for(g in b)b.hasOwnProperty(g)&&(d[e[g]?e[g]:a(g)]=-1==m.indexOf(g)?f(b[g]):b[g]);b=d}}return b}return{compressEvent:f,buildPayload:function(){return u({cs:{dct:D},events:b})}}}();(function(){t.event&&t.event.isStub&&(t.event.replay(function(a){a[3]=a[3]||{};a[3].n=1;A.apply(this,a)}),t.onSushiUnload.replay(function(a){v(a[0])}),t.onSushiFlush.replay(function(a){x(a[0])}))})();
t.attach("beforeunload",g);t.attach("pagehide",g);t._cmps=Q;t.event=A;t.event.reset=function(){J=0};t.onSushiUnload=v;t.onSushiFlush=x;try{d.P&&d.P.register&&d.P.register("sushi-client",z)}catch(f){a.ueLogError(f,{logLevel:"WARN"})}n("ld","ue_sushi_v1",{wb:1})},"Nxs-JS-Client")(ue_csm,window);