(function(g){var p=window.AmazonUIPageJS||window.P,t=p._namespace||p.attributeErrors,b=t?t("CustomerReviewsCommonAssets"):p;b.guardFatal?b.guardFatal(g)(b,window):b.execute(function(){g(b,window)})})(function(g,p,t){g.when("A","cr-log-utils").register("cr-ajax-model",function(b,a){function c(a){f[a]&&(f[a].abort(),delete f[a])}function d(q,n,l,g,k,r,t){var w;w=r?r:h=h++;r=w;k=k?k:n.error||function(){};g=g?g:0;l=l?l:3;var D=n.finallyCallback||function(){};t||(t="reviewsAjax"+e++,p.uet&&p.uet("tc",
t));n.params.scope=t;n.contentType="application/x-www-form-urlencoded;charset=UTF-8";var B=n.success||function(){};n.success=function(a){delete f[r];"function"===typeof B&&B(a);"function"===typeof D&&D(a)};n.error=function(b){c(r);g++;g<l?(a.logError("AJAX Post to "+q+" failed, Attempt: "+g+" out of "+l,"WARN"),d(q,n,l,g,k,r,t)):(a.logError("AJAX Post to "+q+" from "+p.location.href+" failed, exhausted "+l+" attempts","FATAL"),"function"===typeof k&&k(b),"function"===typeof D&&D(b))};f[r]=b.post(q,
n);return r}var e=0,h=1,f={};return{abort:c,post:d}});g.when("A","jQuery").register("cr-A",function(b,a){var c={top:-100,left:-100};b.inView=function(b){b=b||a();if("function"===typeof b.offset){var e=(b.offset()||c).top-a(p).scrollTop();b=0<=e;e=e<a(p).height();return b&&e}return!1};b.onScreenAndVisible=function(){b.onScreen.apply(this,arguments)};return b});g.declare("reviews-constants",{PUSH_STATE:!0,REPLACE_STATE:!1,RATING_SERVICE_CONTEXT_ID:"ReviewsConsumption",data:{REFTAG:"data-reftag",
CSM_COUNTER:"data-csm-counter",getReviews:{STANDARD:"data-reviews-state-param",CHECKED:"data-reviews-param-checked",UNCHECKED:"data-reviews-param-unchecked"}},events:{CONTENT_CHANGED:"reviews:content-changed",RELOAD:"reviews:content-reload",RELOAD_COMPLETE:"reviews:content-reload-complete",AUTOSCROLL_COMPLETE:"reviews:autoscroll-complete",FILTER_FIRE_AGGREGATE:"reviews:filter-action:aggregate:trigger",FILTER_FIRE_UPDATE:"reviews:filter-action:trigger",FILTER_AGGREGATE:"reviews:filter-action:aggregate",
FILTER_PUSH:"reviews:filter-action:push-state",FILTER_REPLACE:"reviews:filter-action:replace-state",PAGINATION:"reviews:page-action",SEARCH_TEXTBOX:"reviews:search-textbox",SEARCH_BUTTON:"reviews:search-button",VOTE:"reviews:vote-action",TOGGLE_CLASS_CLICK:"reviews:toggle-class:click",INPUT_COMMENT:"reviews:input-comment",SUBMIT_COMMENT:"reviews:submit-comment",OPEN_SUBMISSION_COMMENT:"reviews:open-comment-submission",SORT_COMMENTS:"reviews:sort-comments",MORE_COMMENTS:"reviews:more-comments",EDIT_COMMENT:"reviews:edit-comment",
CANCEL_EDIT_COMMENT:"reviews:cancel-edit-comment",DELETE_COMMENT:"reviews:delete-comment",SUBMIT_EDIT_COMMENT:"reviews:submit-edit-comment",MODIFY_EDIT_COMMENT:"reviews:modify-edit-comment",INPUT_PRODUCT_LINK:"reviews:input-product-link",SELECT_PRODUCT_LINK:"reviews:select-product-link",FEEDBACK_CLICK:"reviews:skyfall-feedback-click",CLIQUE_CLICK:"reviews:skyfall-clique-click",STAR_RATING_CLICK:"ryp:star-rating-click",STAR_RATING_CLEAR:"ryp:star-rating-clear-click"},filterOptions:{SORT_KEY:"sortBy",
HELPFUL:"helpful",RECENT:"recent",LEGACY_HELPFUL:"byRankDescending",LEGACY_RECENT:"bySubmissionDateDescending",MOBILE_HELPFUL:"sh",MOBILE_RECENT:"sd",STAR_KEY:"filterByStar",ALL_STARS:"all_stars",ONE_STAR:"one_star",TWO_STAR:"two_star",THREE_STAR:"three_star",FOUR_STAR:"four_star",FIVE_STAR:"five_star",POSTIVE:"positive",CRITICAL:"critical",FORMAT_KEY:"formatType",ALL_FORMATS:"all_formats",CURRENT_FORMAT:"current_format",AVP_KEY:"reviewerType",ALL_REVIEWS:"all_reviews",AVP_ONLY:"avp_only_reviews"},
keycodes:{ENTER:13,BACK_SPACE:8,SPACE:32},aui:{HIDDEN:"aok-hidden",NOWRAP:"aok-nowrap"}});g.when("A","cr-string-utils","cr-log-utils").register("cr-popup",function(b,a,c){function d(d){var h={};d&&d.data&&(h=d.data);var f=a.defaultIfBlank(h.url,d.$target.find("a").andSelf().filter("a").attr("href")),q=a.defaultIfBlank(h.title,"CustomerReviews"),q=""+q,n="";b.each({width:"500",height:"500",resizable:"1",scrollbars:"1",toolbar:"0",status:"1"},function(b,c){var d=a.defaultIfBlank(h[c],b);
n+=c+"="+d+","});var n=n.slice(0,-1),l=null;try{(l=p.open(f,q,n))?l.focus():c.logError("Unable to move focus to popup window with data: "+a.stringify(h),"ERROR"),d.$event.preventDefault()}catch(g){c.logError("Unable to open window with parameters: "+a.stringify(h),"FATAL",g)}return l}b.declarative("cr-popup",["click"],c.jsGuard(d));return{popup:d}});g.when("A","jQuery","reviews-constants").register("cr-generic-declarative-actions",function(b,a,c){function d(b){b&&b.data&&b.data.selector&&
b.data.cssClass&&b.$event&&"function"===typeof b.$event.preventDefault&&(a(b.data.selector).toggleClass(b.data.cssClass),b.$event.preventDefault())}b.declarative(c.events.TOGGLE_CLASS_CLICK,"click",d);return{toggleCssClass:d}});g.when("A","ready").register("cr-global-model",function(b){var a=b.state("reviews-page-state");a||(a=b.$("#cr-state-object").data("state"));var c=null;a&&(c=a.customerId);return{generateUrl:function(a,b){var c=a;c&&"/"!==c.charAt(c.length-1)&&(c+="/");c&&b&&(c=
c+"ref="+b);return c},isSignedIn:function(){return c?!0:!1}}});g.when("A","a-expander","jQuery","reviews-constants","cr-string-utils").register("cr-global-view",function(b,a,c,d,e){function h(a){var b="";if(a&&a.closest!==t){var c=a.closest("*["+g.REFTAG+"]");c&&(b=c.attr(g.REFTAG))}e.isBlank(b)&&a&&a.closest!==t&&(a=a.closest("*[rel]"))&&(b=a.attr("rel"));return e.defaultIfBlank(b,"cm_cr_unknown")}function f(a){return a&&"function"===typeof a.is?a.is("*["+g.getReviews.CHECKED+"]")&&
a.is("*["+g.getReviews.UNCHECKED+"]"):!1}function q(a){return a&&a.has!==t&&a.is!==t?0<a.find(":checked").length||a.is(":checked"):!1}function n(a,b){return a&&a.attr!==t&&b?e.parseJSON(a.attr(b))||{}:{}}function l(a){return a!==t}var g=d.data;b.on("a:expander:review_text_read_more:toggle:collapse",function(a){l(a)&&l(a.expander)&&l(a.expander.$expander)&&1===a.expander.$expander.length&&l(a.expander.$expander[0].closest(".review"))&&l(a.expander.$expander[0].closest(".review").offsetTop)&&(a=a.expander.$expander[0].closest(".review").offsetTop,
p.scroll(0,a))});b.on("a:pageUpdate",function(){l(a)&&a.initializeExpanders()});return{getReviewsStateParamsFromElement:function(a){var c=b.reduce(g.getReviews,function(a,b){return a+"*["+b+"],"},"").slice(0,-1),d;c&&a&&a.closest!==t&&(d=a.closest(c));return f(d)?q(d)?n(d,g.getReviews.CHECKED):n(d,g.getReviews.UNCHECKED):n(d,g.getReviews.STANDARD)},getReftag:function(a){var b;a&&a.$target&&(b=a.$target);a&&a.id&&(b=c("#"+a.id));a&&a.expander&&a.expander.$expander&&(b=a.expander.$expander);b=h(b);
"cm_cr_unknown"===b&&a&&a.data&&a.data.reftag&&(b=a.data.reftag);return b},getReftagByDom:h,scrollTo:function(a,b){var d=c(a).offset(),e=b||0,f=c("#cr-state-object").data("state"),f=f!==t&&f.disableScroll;d&&d.top!==t&&!f&&(c("html,body").stop(),c("html,body").animate({scrollTop:d.top-e},{queue:!1,duration:500}))}}});g.when("A").register("cr-log-utils",function(b){function a(a,b,c){p.ueLogError&&("string"!==typeof b&&(b="FATAL"),c?p.ueLogError(c,{message:a,logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}):
p.ueLogError({message:a},{logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}))}function c(a,b){return"string"===typeof b?b+a:"CustomerReviews:"+a}return{logError:a,jsGuard:function(b){if("function"===typeof b)return function(){try{return b.apply(this,arguments)}catch(c){a("Uncaught Error in function","FATAL",c)}};a("Unable to wrap non-function","ERROR");return b},incrementCount:function(a,b){if(p.ue){var h=c(a,b),f=p.ue.count(h)||0;p.ue.count(h,f+1)}},logCount:function(a,b,h){p.ue&&(a=c(a,
h),p.ue.count(a,b))}}});g.register("cr-mash-utils",function(){var b=!1;g.when("mash").execute(function(){b=!0});return{isMash:function(){return b}}});g.when("A","cr-log-utils").register("cr-number-utils",function(b,a){return{convertToInteger:function(b,d){if(b===parseInt(b,10))return b;if(null!==b&&b!==t&&""!==b)return parseInt(b.replace(/[^0-9]/g,""),10);if(d!==t)return d;a.logError("convertToInteger","Cannot convert "+b+" to Integer");return 0}}});g.when("cr-A",
"jQuery","cr-string-utils","afterReady").register("cr-on-view-utils",function(b,a,c){function d(a,c){if(!f[a]){var d=e(a,c)();q[a]=(q[a]||[]).concat(d);b.on.scroll(d)}}function e(c,d){return function k(){b.inView(a(c))&&(h(c,d),b.each(q[c]||[],function(a){b.off("scroll",a)}));return k}}function h(a,c){f[a]||(f[a]=!0,b.post(c.ajaxUrl,{params:c.ajaxParamsMap||{}}))}var f={},q={};b.each(a("*[data-cr-trigger-on-view]"),function(b,e){var f=a(b),h=f.attr("data-cr-trigger-on-view"),h=c.parseJSON(h);if(null!==
h){var q="cr-trigger-on-view-"+e;f.addClass(q);d("."+q,h)}});return{triggerOnScrollIntoView:d,trigger:h}});g.when("A","jQuery").register("cr-streaming-utils",function(b,a){return{appendFadeIn:function(c){if(null!==c&&2<c.length&&null!==c[1]&&null!==c[2]){var d=c[1];c=a(c[2]).hide();a(d).append(c);b.fadeIn(c,500,"ease-in-out",function(){})}}}});g.when("A","cr-log-utils").register("cr-string-utils",function(b,a){function c(a){return null===a||a===t?!0:0===b.trim(a).length}
return{defaultIfBlank:function(a,b){return c(a)?b:a},isBlank:c,parseJSON:function(c){try{return b.parseJSON(c)}catch(e){a.logError("Unable to parse JSON object","ERROR",e)}return null},startsWith:function(a,b){return a===b?!0:null===a||null===b?!1:0===a.indexOf(b)},stringify:function(a){return p.JSON&&p.JSON.stringify?p.JSON.stringify(a):a}}});g.when("A","cr-string-utils","3p-urijs").register("cr-uri-utils",function(b,a,c){function d(){return c(p.location.href)}function e(){return d().query()}
return{getCurrentUri:d,getCurrentQueryString:e,getCurrentQueryParameters:function(){return c.parseQuery(e())},isAmazonDomain:function(b){if("string"===typeof b||b instanceof String)b=c(b);var d=a.startsWith(b.domain(),"amazon");!1===d&&(b=b.hostname(),b=b.substring(b.indexOf(".")+1),d=a.startsWith(b,"amazon"));return d},setQueryParameters:function(d,e){if("string"===typeof d||d instanceof String)d=c(d);b.each(e,function(b,c){a.isBlank(b)?d.removeSearch(c):d=d.setSearch(c,b)});return d},setReftag:function(b,
d){if("string"===typeof b||b instanceof String)b=c(b);for(var e=b.segment(),g=!1,l=e.length-1;0<=l;l--)if(a.startsWith(e[l],"ref=")){g=!0;e[l]="ref="+d;break}g||e.push("ref="+d);b.segment(e);return b}}});g.when("cr-A","jQuery","cr-log-utils","cr-string-utils","afterReady").register("cr-weblab-utils",function(b,a,c,d){function e(d,e,f,p){g[e]||(c.logCount(f,0,p),d=h(a(d),e,f,p)(),n[e]=(n[e]||[]).concat(d),b.on.scroll(d))}function h(a,c,d,e){return function w(){b.inView(a)&&(f(c,d,e),b.each(n[c]||
[],function(a){b.off("scroll",a)}));return w}}function f(a,d,e){g[a]||(g[a]=!0,b.post("/ss/customer-reviews/ajax/weblab-trigger",{params:{weblabId:a}}),c.logCount(d,1,e))}var g={},n={};b.each(a("*[data-cr-weblab-trigger-on-scroll]"),function(b,c){var f=a(b),h=f.attr("data-cr-weblab-trigger-on-scroll"),h=d.parseJSON(h);if(null!==h){var g="cr-weblab-trigger-on-scroll-"+c;f.addClass(g);e("."+g,h.weblabId,h.metricName,h.prefix)}});return{triggerOnScrollIntoView:e,triggerWeblab:f}});g.when("A").register("histogram-trigger",
function(b){function a(){b.onScreen(b.$("#histogramTable"))&&b.trigger("scroll")}b.on.afterLoad(a);return{triggerHistogram:a}})});